### ISSUE TITLE
Issue with xml ENTITY

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-website#1005]
Somehow the `serverRPMMinorVersion` entity isn't working correctly, see https://www.rabbitmq.com/download.html

```
https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.5/rabbitmq-server-3.8.5-&serverRPMMinorVersion;.el8.noarch.rpm
```

The `serverDebMinorVersion` entity appears to be working correctly.

Running `make preview` works locally so this must have something to do with the latest deployment.

**Comment by michaelklishin** [comment]
We hardcoded the value for now. I don't have an explanation as to why only one entity fails to render but not several others on the same page (it is not a typo).
