### ISSUE TITLE
Java Client build instruction are broken

### ISSUE THREAD

**Issue by binarin** [rabbitmq/rabbitmq-website#102]
After 0d1b2bd0e84b8f77b2f62d4ee90983458baef02d, the expected path to codegen directory changed from `rabbitmq-codegen` to `rabbitmq_codegen`. As commit message mentions erlang.mk layout, I assume that it is the docs that need updating.

**Comment by michaelklishin** [comment]
Your understanding is very likely correct. We haven't updated all docs and plugins for erlang.mk yet.
