### ISSUE TITLE
list_unresponsive_queues queue_timeout or queue-timeout?

### ISSUE THREAD

**Issue by GitHubPang** [rabbitmq/rabbitmq-website#1024]
In [the man page for `rabbitmqctl`](https://www.rabbitmq.com/rabbitmqctl.8.html#list_unresponsive_queues), for the command `list_unresponsive_queues`, it says there's an option named `queue_timeout`. However, when I run the following command in RabbitMQ 3.8.5:
```
rabbitmqctl list_unresponsive_queues --queue_timeout 20 --local name
```

I got an error:

```
Error (argument validation): Invalid options for this command:
--queue_timeout :
Arguments given:
        list_unresponsive_queues --queue_timeout 20 --local name

Usage

rabbitmqctl [--node <node>] [--longnames] [--quiet] list_unresponsive_queues [--local] [--queue-timeout <milliseconds>] [<column> ...] [--no-table-headers] [--timeout <timeout>]
```

which indicates that the option is named `queue-timeout` (with a _hyphen_) instead of `queue_timeout` (with an _underscore_).

So either the man page is wrong or the command is wrong.

**Comment by michaelklishin** [comment]
Note that the help message says `--queue-timeout` and this works:

``` shell
rabbitmq-diagnostics list_unresponsive_queues --queue-timeout 5000
```

so this is a man page typo. You can find man pages [in the server repository](https://github.com/rabbitmq/rabbitmq-server/tree/master/docs) in case you'd like to submit a PR.
