### ISSUE TITLE
Queue length documentation incorrect

### ISSUE THREAD

**Issue by stderr-to-devnull** [rabbitmq/rabbitmq-website#1029]
https://www.rabbitmq.com/maxlength.html
...it states that:
"The fields `messages_ready` and `message_bytes_ready` from `rabbitmqctl list_queues` and the management API show the values that would be limited."

This is incorrect, I just checked:
```
rabbitmqctl list_queues name messages_ready
Timeout: 60.0 seconds ...
Listing queues for vhost / ...
name    messages_ready
test_queue  0
```

My `x-max-length` limit value only shows up when checking the queue in the web console.

**Comment by michaelklishin** [comment]
The docs try to explain that the number of messages in Ready state (and their bytes) is subject to limiting. We will see how this can be communicated clearer.

I’m not sure what your `list_queue` example proves; the command is not meant to display the limit, you have to list policies for that.

**Comment by stderr-to-devnull** [comment]
@michaelklishin I just followed precisely what the documentation said. The "show the values that would be limited" part from my original quote. I am not sure what else a reader is supposed to understand but for me it says "give that command to show the limits". Also this was not set up as a policy but as a queue argument, like the same documentation says it can be done.

**Comment by michaelklishin** [comment]
@stderr-to-devnull I have changed the language, see the commits above. Yes, a limit can be set an optional queue argument but that is [highly discouraged](https://www.rabbitmq.com/parameters.html#why-policies-exist) because all queue properties are immutable.

I will add a note on how to inspect the limits.

**Comment by stderr-to-devnull** [comment]
@michaelklishin Thank you, appreciated.
