### ISSUE TITLE
x-quorum-queue-size: An outdated reference?

### ISSUE THREAD

**Issue by Asgavar** [rabbitmq/rabbitmq-website#1053]
The quorum queues doc's section on fault tolerance[1] says, quoting:

> The default quorum queue size is 5 and is controllable using the x-quorum-queue-size queue argument.

Is that argument still relevant? I couldn't find any mentions of it anywhere else, and it sounds like it would be quite similar to what `x-quorum-initial-group-size`, referred to by the very same doc btw, does.

[1] https://github.com/rabbitmq/rabbitmq-website/blob/62079b958e9038c673e9393c501d1380a55f4a6c/site/quorum-queues.md#quorum-requirements

**Comment by michaelklishin** [comment]
Yes, this key was renamed to `x-quorum-initial-group-size` before 3.8.0, thanks for spotting.
