### ISSUE TITLE
Broken link to advanced config sample in "configure.md"

### ISSUE THREAD

**Issue by Ricordel** [rabbitmq/rabbitmq-website#1095]
In the following section of "configure.md":

> The RabbitMQ server source repository contains an example advanced.config file named advanced.config.example. It focuses on the options that are typically set using the advanced config.

the link to `advanced.config`, pointing to https://github.com/rabbitmq/rabbitmq-server/blob/master/docs/advanced.config.example, is broken (404). I cannot find where this file was moved.

**Comment by michaelklishin** [comment]
It was moved [over here](https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbit/docs/advanced.config.example) when all repositories were combined into one.

**Comment by Ricordel** [comment]
Thank you very much!
