### ISSUE TITLE
On Services Page - external link to Open Source Architect is broken.

### ISSUE THREAD

**Issue by david-harkness** [rabbitmq/rabbitmq-website#1103]
On this page https://www.rabbitmq.com/services.html
Under "Training"
there is an external link to "Open Source Architect." that goes here https://opensource.io/product/rabbitmq-training/

Link has a certificate error, and just goes to a 404 page.

https://github.com/rabbitmq/rabbitmq-website/blob/0f50b550fb2fe03fb501468e984eb70de08e6ed7/site/services.md

**Comment by michaelklishin** [comment]
It was removed, thank you for bringing this up.
