### ISSUE TITLE
Tutorial 7   python program

### ISSUE THREAD

**Issue by AronWater** [rabbitmq/rabbitmq-website#1117]
for tutorial 7 https://www.rabbitmq.com/tutorials/tutorial-seven-java.html,
only java, C# or PHP is available,
I wonder if python version could also be released.
Million thanks

**Comment by michaelklishin** [comment]
This is open source software. You are welcome to contribute it.

**Comment by michaelklishin** [comment]
Pika has a [publisher confirms example](https://github.com/pika/pika/blob/master/examples/confirmation.py) FWIW.
