### ISSUE TITLE
doc: busy waiting link leading to quorum queues page

### ISSUE THREAD

**Issue by deronnax** [rabbitmq/rabbitmq-website#1118]
Hello.
In the [Reducing CPU Usage section of the runtime doc](https://www.rabbitmq.com/runtime.html#busy-waiting), there is a sentence which is _CPU resources can be wasted while nodes are busy waiting for I/O operations._, and the _busy waiting for I/O operations_ links to the page [Quorum queues and why disks matter](https://www.rabbitmq.com/blog/2020/04/21/quorum-queues-and-why-disks-matter/). But that quorum queue page does not say a word about busy waiting. If it's a mistake, I have no idea what was the original author's intent to link to. 
If it's not, please explain in a few words why not (so other people wondering and running into this issue can figure out) and you can dismiss this issue.
Thank you.

**Comment by michaelklishin** [comment]
That section was added in https://github.com/rabbitmq/rabbitmq-website/commit/b51a7310ed092d8da2829ce418b108d23e14f387 six months ago. I don't remember all the details but the post does try to explain that disk I/O can easily be a bottleneck for some parts of the system, and the busy waiting scheduler metric reflects that.

**Comment by michaelklishin** [comment]
Thank you for bringing this up.
