### ISSUE TITLE
Feedback to install RabbitMQ on Ubuntu

### ISSUE THREAD

**Issue by manueljordan** [rabbitmq/rabbitmq-website#1177]
Hello.

I am sharing my experience and feedback about how to install RabbitMQ on Ubuntu.
Currently there are missing instructions, few errors and seems redundant information to be removed

So - based on: **Using RabbitMQ Apt Repositories on Cloudsmith**

It because the _Using RabbitMQ Apt Repositories on PackageCloud_ approach always fails with:

```
## Launchpad PPA that provides modern Erlang releases
sudo apt-key adv --keyserver "keyserver.ubuntu.com" --recv-keys "F77F1EDA57EBB1CC"
```
is **not** possible get the connection, connection timeout

Ok, so with _Using RabbitMQ Apt Repositories on Cloudsmith_ I only did do the following:

**Enable apt HTTPS Transport**

* `sudo apt install apt-transport-https`

**Add Repository Signing Key**

``` 
## Team RabbitMQ's main signing key
sudo apt-key adv --keyserver "hkps://keys.openpgp.org" --recv-keys "0x0A9AF2115F4687BD29803A206B73A36E6026DFCA"
Cloudsmith: modern Erlang repository
curl -1sLf https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key | sudo apt-key add -
## Cloudsmith: RabbitMQ repository
curl -1sLf https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key | sudo apt-key add -
```

**Note**: from above - must be `sudo apt-key add -` (the `sudo` part is mandatory), Otherwise:

```
E: This command can only be used by root.
(23) Failed writing body
```
**Add a Source List File**

* Go to the `/etc/apt/sources.list.d/` directory
* Create the `sudo nano rabbitmq.list` file 

**Warning**: is mentioned _incorrectly_ the `/etc/apt/sources.list.d` file, in the sentence:

```
To add the apt repository to the source list directory (/etc/apt/sources.list.d), use:
``` 

All is based in the `/etc/apt/sources.list.d/rabbitmq.list` file (different path location and file's name)

Add the following (be sure to replace `$distribution`):

```
## Provides modern Erlang/OTP releases
##
## Replace $distribution with the name of the Ubuntu release used.
## On Debian, "deb/ubuntu" should be replaced with "deb/debian"
deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu $distribution main
deb-src https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu $distribution main

## Provides RabbitMQ
##
## Replace $distribution with the name of the Ubuntu release used.
## On Debian, "deb/ubuntu" should be replaced with "deb/debian"
deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu $distribution main
deb-src https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu $distribution main
```

**Install Packages**

* `sudo apt update -y`

```
## Install Erlang packages
sudo apt-get install -y erlang-base \
                        erlang-asn1 erlang-crypto erlang-eldap erlang-ftp erlang-inets \
                        erlang-mnesia erlang-os-mon erlang-parsetools erlang-public-key \
                        erlang-runtime-tools erlang-snmp erlang-ssl \
                        erlang-syntax-tools erlang-tftp erlang-tools erlang-xmerl

## Install rabbitmq-server and its dependencies
sudo apt-get install rabbitmq-server -y --fix-missing
```

That's all. So I got:

```
sudo systemctl status rabbitmq-server
● rabbitmq-server.service - RabbitMQ broker
   Loaded: loaded (/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-05-07 09:17:37 -05; 3min 36s ago
 Main PID: 5712 (beam.smp)
   Status: "Initialized"
    Tasks: 22 (limit: 4608)
   CGroup: /system.slice/rabbitmq-server.service
           ├─5712 /usr/lib/erlang/erts-11.2.1/bin/beam.smp -W w -MBas ageffcbf -MHas ageffcbf -MBlmbcs 512 -MHlmbcs 512 -MMmcs 30 -P 1048576 -t 5000000 -stbt db 
           ├─5723 erl_child_setup 32768
           ├─5748 /usr/lib/erlang/erts-11.2.1/bin/epmd -daemon
           ├─5768 inet_gethost 4
           └─5769 inet_gethost 4

May 07 09:17:33 asus2016-vb01 rabbitmq-server[5712]:   ##########  Licensed under the MPL 2.0. Website: https://rabbitmq.com
May 07 09:17:33 asus2016-vb01 rabbitmq-server[5712]:   Doc guides: https://rabbitmq.com/documentation.html
May 07 09:17:33 asus2016-vb01 rabbitmq-server[5712]:   Support:    https://rabbitmq.com/contact.html
May 07 09:17:33 asus2016-vb01 rabbitmq-server[5712]:   Tutorials:  https://rabbitmq.com/getstarted.html
May 07 09:17:33 asus2016-vb01 rabbitmq-server[5712]:   Monitoring: https://rabbitmq.com/monitoring.html
May 07 09:17:33 asus2016-vb01 rabbitmq-server[5712]:   Logs: /var/log/rabbitmq/rabbit@asus2016-vb01.log
May 07 09:17:33 asus2016-vb01 rabbitmq-server[5712]:         /var/log/rabbitmq/rabbit@asus2016-vb01_upgrade.log
May 07 09:17:33 asus2016-vb01 rabbitmq-server[5712]:   Config file(s): (none)
May 07 09:17:37 asus2016-vb01 rabbitmq-server[5712]:   Starting broker... completed with 0 plugins.
May 07 09:17:37 asus2016-vb01 systemd[1]: Started RabbitMQ broker.
```
I respect your work. - The goal is that the installation process be practical and quick. 

Thanks for your understanding

**Comment by manueljordan** [comment]
I am going to close this, it was created mostly to share a quick summary. Of course only for one specific distribution.

Thanks for all

**Comment by michaelklishin** [comment]
You were correct in pointing out that the individual PackageCloud snippets were piping to `apt-key` without invoking it with `sudo`. That should be corrected now.

Using Cloudsmith is arguably easier. PackageCloud  and Launchpad are used and documented primarily as a backup option. Do you have prior experience with PackageCloud or were there any reasons to choose this option?
Not that there's anything wrong with that, of course.

**Comment by manueljordan** [comment]
I chose first _on PackageCloud and Launchpad_ because I know Ubuntu works with `Launchpad` but I got the connection failure scenario, so I moved to _on Cloudsmith_. That's all, furthermore the latter uses `apt-key add -` that I read in many tutorials.

**Comment by michaelklishin** [comment]
OK, thanks. Maybe a separate Ubuntu guide is unavoidable… then at least it could make certain Ubuntu-specific assumptions 🤔
