### ISSUE TITLE
IRC channel review

### ISSUE THREAD

**Issue by Pimmetje** [rabbitmq/rabbitmq-website#1215]
Due to changes at Freenode, a lot of projects moved there IRC channel. 

Please review it and if needed changes the documentation on https://www.rabbitmq.com/contact.html

**Comment by michaelklishin** [comment]
We haven't moved our IRC channel, so there is nothing to change at the moment. If we move it, the docs obviously will be updated.

Most of our community uses [community Slack](https://www.rabbitmq.com/contact.html) these days.
