### ISSUE TITLE
Misleading sentence

### ISSUE THREAD

**Issue by tasmaniski** [rabbitmq/rabbitmq-website#125]
In second tutorial there is no scheduled messages in real meaning 
(as https://github.com/rabbitmq/rabbitmq-delayed-message-exchange)

>_The main idea behind Work Queues (aka: Task Queues) is to avoid doing a resource-intensive task immediately and having to wait for it to complete. **Instead we schedule the task to be done later.** We encapsulate a task as a message and send it to a queue..._ 

The link: https://www.rabbitmq.com/tutorials/tutorial-two-php.html 
I can provide PR, but don't know if that is the culture here :)

**Comment by michaelklishin** [comment]
I'm not sure "the real meaning" is "delayed message exchange". Semantically publishing a message for other apps to act on at a later point is "delaying".

What would your PR correct?

**Comment by videlalvaro** [comment]
Also "scheduling" is not about _doing tasks later_, but about assigning tasks to processors using certain queue discipline, like FIFO + kinda round robin like RabbitMQ does.

**Comment by tasmaniski** [comment]
Aha, yes, there is a point what you are saying. 

When I was reading the article I was looking for delayed message because of 
"Instead we schedule the task to be done later." ... probably is only my perception :) 

Anyhow the issue can be closed.
Thanks!
