### ISSUE TITLE
Add RabbitMQ Ballerina lang client to Client Libraries section

### ISSUE THREAD

**Issue by aashikam** [rabbitmq/rabbitmq-website#1269]
[Ballerina](https://ballerina.io/) lang provides support for RabbitMQ. It would be great if you could mention the Ballerina client for RabbitMQ in https://www.rabbitmq.com/devtools.html.  

## References

**Ballerina:**
Site: https://ballerina.io/
Central: https://central.ballerina.io/

**RabbitMQ client:** 
Package: **ballerinax/rabbitmq**
Latest: https://central.ballerina.io/ballerinax/rabbitmq
Source: https://github.com/ballerina-platform/module-ballerinax-rabbitmq

**Comment by michaelklishin** [comment]
We add libraries to that page when they reach certain maturity. I have never heard of Ballerina, in the RabbitMQ community or in general.

You are welcome to promote this client on our community Slack or the `rabbitmq-users` Google group, of course.
