### ISSUE TITLE
Fix incorrect link at: Installing on Debian and Ubuntu

### ISSUE THREAD

**Issue by manueljordan** [rabbitmq/rabbitmq-website#1296]
In the [Installing on Debian and Ubuntu](https://www.rabbitmq.com/install-debian.html) page in the top does mention about 

```
Team RabbitMQ produces our own Debian packages and distributes them using Cloudsmith and PackageCloud.
```
The first `using Cloudsmith` link targets how is expected to the `Using RabbitMQ Apt Repositories on Cloudsmith` section through the following URL:

* https://www.rabbitmq.com/install-debian.html#apt-cloudsmith

Now the  `Using RabbitMQ Apt Repositories on Cloudsmith` section itself refers incorrectly to the following URL:

* https://www.rabbitmq.com/install-debian.html#apt

About the plain text URLs observe the former ends with `#apt-cloudsmith` and the latter ends with `#apt`. So the latter must be the same how the former.

**Comment by michaelklishin** [comment]
@manueljordan you are welcome to [submit a PR](https://github.com/rabbitmq/rabbitmq-website/blob/live/site/install-debian.md).

**Comment by manueljordan** [comment]
@michaelklishin  Ok, I am going to this, but let me read all the file in case there are more cases like this
