### ISSUE TITLE
Date of updates issue

### ISSUE THREAD

**Issue by duch94** [rabbitmq/rabbitmq-website#1302]
I noticed that you have bug with dates of releases on your web page. 
On main at the bottom right of the page RabbitMQ version 3.8.25 have date of release of 11 Dec 2021. But if you dive into "more updates" you will see that it is 12 Nov 2021. Looks like it is some frontend issue with date types. Below you can see this bug on screenshots.

<img width="345" alt="Снимок экрана 2021-11-15 в 12 44 47" src="https://user-images.githubusercontent.com/19227122/141762598-8916f80d-2ea2-48cd-aa7d-3fb9019192ed.png">
<img width="1440" alt="Снимок экрана 2021-11-15 в 12 44 54" src="https://user-images.githubusercontent.com/19227122/141762606-bb254558-526b-42b3-bcdc-393283fca9ca.png">

**Comment by michaelklishin** [comment]
It was a typo in the release date. Good catch.

**Comment by michaelklishin** [comment]
I'm not sure when the sidebar will update but the input data it uses is correct now.

**Comment by duch94** [comment]
> I'm not sure when the sidebar will update but the input data it uses is correct now.

It have updated, now date is correct. Thanks!
