### ISSUE TITLE
Several pages don't have breadcrumb

### ISSUE THREAD

**Issue by tranvansang** [rabbitmq/rabbitmq-website#1305]
Somehow I got to several rabbitmq docs pages (see below).
I want to look at the index page of these pages to scan for all available resources.
However, there is no breadcrumb or link to the parent page from the content.

Can anyone tell me if there are any sibling pages, or the parent page of the below pages?

https://www.rabbitmq.com/consumers.html

https://www.rabbitmq.com/passwords.html

https://www.rabbitmq.com/connections.html

https://www.rabbitmq.com/queues.html

https://www.rabbitmq.com/tutorials/amqp-concepts.html

By the way, thank you very much for the awesome document website.

**Comment by michaelklishin** [comment]
All of those are pretty self-contained.

**Comment by tranvansang** [comment]
thanks. Is there a list of them?

**Comment by michaelklishin** [comment]
There is no as how you group guides is a matter of opinion.
