### ISSUE TITLE
Broken "using-operator.html" link

### ISSUE THREAD

**Issue by aaabramov** [rabbitmq/rabbitmq-website#1311]
Page: https://www.rabbitmq.com/kubernetes/operator/using-operator.html
Source: https://github.com/rabbitmq/rabbitmq-website/blob/live/site/kubernetes/operator/using-operator.md?plain=1#L31

![image](https://user-images.githubusercontent.com/11317222/144383933-af488ae7-17a3-41c5-96f1-644a9d36e0a0.png)

I was not sure why it's not picking up the link (while it's fine with others similar to this one)

**Comment by michaelklishin** [comment]
Because Markdown anchors won't be rendered in HTML blocks.
