### ISSUE TITLE
Broken Link on Best Practices page

### ISSUE THREAD

**Issue by AyushG3112** [rabbitmq/rabbitmq-website#1368]
The link `RabbitMQ best practices — Part 1` on the https://www.rabbitmq.com/best-practices.html page is broken. It links to https://medium.com/@aloksinghal/rabbitmq-best-practices-part-1-6f66522e4fe which has been deleted by the author.

Looks like it's served via Uberflip so it'll have to be removed from there.

**Comment by pstack2021** [comment]
Fixed now, medium link: https://medium.com/@aloksinghal/rabbitmq-best-practices-part-1-6f66522e4fe is removed.

**Comment by michaelklishin** [comment]
Thank you, @pstack2021.
