### ISSUE TITLE
Broken Link and recommended javascript library for web-stomp?

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [rabbitmq/rabbitmq-website#1369]
Following link is broken: https://github.com/rabbitmq/rabbitmq-website/blob/live/access-control.html

on this page:
https://github.com/rabbitmq/rabbitmq-website/blob/live/site/web-stomp.md

And what is now the recommended javascript library to use?
https://github.com/jmesnil/stomp-websocket/ like mentioned in the example is not maintained anymore?

**Comment by michaelklishin** [comment]
We are not aware of other libraries. `stomp-websocket` still works. If you have other suggestions, we are all ears.

**Comment by h0jeZvgoxFepBQ2C** [comment]
I just found StompJs https://stomp-js.github.io/ which looks like is maintained: https://github.com/stomp-js/stompjs
First test with it also worked for me, so I guess its fine.

**Comment by michaelklishin** [comment]
@h0jeZvgoxFepBQ2C would you like to adapt the docs and [the example plugin](https://github.com/rabbitmq/rabbitmq-server/tree/master/deps/rabbitmq_web_stomp_examples) to use that library, and submit a PR? That would be greatly appreciated 🙏

**Comment by michaelklishin** [comment]
I'm not sure why the link was broken as it seemed correct. It is functional now that https://github.com/rabbitmq/rabbitmq-website/commit/418b72b81c94a34f5fdc33e24fb5c2ecc9054fe0 has been deployed. https://github.com/rabbitmq/rabbitmq-website/commit/2333d869a365d056e27a474a6c20b871987e8291 will follow in a few minutes.
