### ISSUE TITLE
Support for "conf.d" configuration directories and RABBITMQ_CONFIG_FILES are not documented

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-website#1372]
It needs to be as it relates to these issues, PRs and discussions:

* Original PR for the feature - https://github.com/rabbitmq/rabbitmq-server/pull/2258
* Discussions and other issues:
  * https://github.com/rabbitmq/rabbitmq-server/discussions/4319
  * https://github.com/docker-library/rabbitmq/issues/554
  * https://github.com/docker-library/rabbitmq/pull/555
  * https://github.com/docker-library/rabbitmq/issues/506 (many off-put users here)

**Comment by michaelklishin** [comment]
Happy to do it if you'd rather not spend time on docs @lukebakken :)
