### ISSUE TITLE
Clarify that queue mirroring is CP in the docs

### ISSUE THREAD

**Issue by wenjianhn** [rabbitmq/rabbitmq-website#138]
It says that we are able to choose consistency and availability from the CAP theorem [1].

Looks like it's not true according to the following answer.
https://www.quora.com/Whats-the-difference-between-CA-and-CP-systems-in-the-context-of-CAP-Consistency-Availability-and-Partition-Tolerance
"The CAP theorem is woefully badly stated. It's not usefully about a straight choice between C, A and P - it is actually about what you give up if you have a partition. "

[1] https://www.rabbitmq.com/distributed.html

**Comment by michaelklishin** [comment]
It largely depends on how you define each. In the opinion of our current team RabbitMQ queue mirroring is CP. We will look into editing that guide (which hasn't really changed in some 5 years).

**Comment by wenjianhn** [comment]
Since one side of the partition must act as if it is unavailable, I think queue mirroring is CP too.
