### ISSUE TITLE
Revise the RabbitMQ Production Checklist

### ISSUE THREAD

**Issue by pstack2021** [rabbitmq/rabbitmq-website#1382]

**Comment by pstack2021** [comment]
As a Support Person for RabbitMQ/Tanzu/VMware
I want a checklist that is easily readable, the [current one](https://www.rabbitmq.com/production-checklist.html) is very long and there is too much in it

Perhaps have it in the form of its a title - a checklist

**Comment by michaelklishin** [comment]
I'm afraid a production checklist cannot be a few sentences long. There are many aspects to running a distributed data service. We don't hear this opinion voiced in the community, most users are happy that this document covers a lot of ground.

I don't understand the "too much of it" part either. All the sections in that guide come from real world experience over more than a decade.

**Comment by pstack2021** [comment]
Thanks @michaelklishin for this information. This feedback came from an interview the Education and Enablement charter conducted with a Tanzu Support person. 

I wonder could we make some minor improvements - a list of quick links at the top of the Production Checklist page taking you to each of the sections further down the page, for example:

[Overview](https://www.rabbitmq.com/production-checklist.html#overview) (2 Overview sections - combine into 1 maybe) 
[Virtual Hosts, Users, Permissions](https://www.rabbitmq.com/production-checklist.html#users-and-permissions)
......

Perhaps include some clear instructions at the start of the Production checklist on how to use it to get the best out of it?

**Comment by michaelklishin** [comment]
I have added a ToC earlier today. We can re-arrange sections, add new ones and emphasise some over others.

**Comment by pstack2021** [comment]
Thanks @michaelklishin have a great weekend

**Comment by pstack2021** [comment]
I will actually close this issue @michaelklishin and open a separate one for the review, thank you very much for taking the time to complete the updates above.
