### ISSUE TITLE
heartbeat documentation is inconsistent

### ISSUE THREAD

**Issue by cressie176** [rabbitmq/rabbitmq-website#1386]
The [heartbeat documentation](https://www.rabbitmq.com/heartbeats.html) contains the following statements

> A zero value indicates that a peer suggests disabling heartbeats entirely. To disable heartbeats, both peers have to opt in and use the value of 0

and

> Heartbeats can be disabled by setting the timeout interval to 0 on the client side at connection time.

The second statement incorrectly implies that the server heartbeat does not also need to be set to zero in order for the heartbeat to be disabled

**Comment by lukebakken** [comment]
We would welcome a PR to update the documentation. FWIW, disabling heartbeats is never recommended.

**Comment by michaelklishin** [comment]
Closed by #1387 #1388 with minor adjustments from me.
