### ISSUE TITLE
Update JMS reference documentation

### ISSUE THREAD

**Issue by epomatti** [rabbitmq/rabbitmq-website#1395]
Hi

The very first link in the documentation is pointing to an [archived repository](https://github.com/rabbitmq/rabbitmq-jms-topic-exchange), which has been migrated to the official Rabbit monolith repository 2 years ago.

https://www.rabbitmq.com/jms-client.html#introduction

This documentation should be updated to reflect the new repository, but also any other outstanding changes that should be presented upfront for developers.

**Comment by michaelklishin** [comment]
The website repository is open source so you are welcome to do it.
