### ISSUE TITLE
Link to rabbitmq.config.example

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-website#142]
…from `/configure.html`.

**Comment by hairyhum** [comment]
How can we get link to latest released version in docs? Setting it directly during release don't sound like a good idea.

**Comment by michaelklishin** [comment]
If you mean "how can we link to a specific tag on GitHub", we [already do this](https://github.com/rabbitmq/rabbitmq-website/blob/master/site/rabbit.ent#L26) in multiple places.

**Comment by hairyhum** [comment]
Is it set automatically during release process?

**Comment by michaelklishin** [comment]
It is [updated manually](https://github.com/rabbitmq/rabbitmq-website/commit/e51eb1161c4ccc33af685db47c7e546913f95d40) when we prepare to deploy a release.
