### ISSUE TITLE
Ask a rabbitmq persistence question

### ISSUE THREAD

**Issue by kgyinspur** [rabbitmq/rabbitmq-website#1477]
How to disable local disk persistence in rabbitmq？

**Comment by michaelklishin** [comment]
Consider using GitHub Discussions for questions.

Future RabbitMQ versions will drop support for most transient entities, and new features like quorum queues and streams always persist. So I am not going to explain the closest currently available option.

Exclusive queues will remain so if you really need to make your data transient, use them. For most workloads this would not make much sense.
