### ISSUE TITLE
management UI login screen is vulnerable to cross-frame scripting attack

### ISSUE THREAD

**Issue by bdmcfarland7** [rabbitmq/rabbitmq-website#149]
A security scan on the login screen of the management UI revealed that a cross-frame scripting attack could be achieved.  Here are some notes from the scan results.

"Create a test page containing an HTML iframe tag whose src attribute is set to
http://<server>:<port>/js/tmpl/login.ejs?0.6482927613997587. Successful framing of the target page
indicates the application’s susceptibility to XFS."

"This response is not protected by a valid X-Frame-Options header.Furthermore,
An effective frame-busting technique was not observed while loading this page inside a frame."

**Comment by michaelklishin** [comment]
This repository is for documentation, not management pkugin. Responsible vulnerability disclosures are expected via a private channel, info@rabbitmq.com. Please keep this in mind for the future.
