### ISSUE TITLE
Updates 1.2 and 1.3 Tanzu Docs for exclusive features name changes 

### ISSUE THREAD

**Issue by pstack2021** [rabbitmq/rabbitmq-website#1492]
Doc Actions:

1. Complete updates in Tanzu docs to rename exclusive features to be in inline with the following agreed names: 
https://miro.com/app/board/uXjVOptQba8=/
2. Remove OSS pages with these exclusive features from the Tanzu doc set, they are Tanzu only features which have their own Tanzu feature pages

Name Changes to be implemented:
Standby Replication -> Warm Standby Replication
Inter-node and CLI Traffic Compression to Intra-cluster Compression

**Comment by pstack2021** [comment]
Updates above are complete, see:
For 1.2 release: https://docs.vmware.com/en/VMware-Tanzu-RabbitMQ-for-Kubernetes/1.2/tanzu-rmq/GUID-tanzu-rabbitmq-features.html
For 1.3 release: https://docs.vmware.com/en/VMware-Tanzu-RabbitMQ-for-Kubernetes/1.3/tanzu-rmq/GUID-tanzu-rabbitmq-features.html

OSS Pages documenting these features are now removed from the 1.2 and 1.3 doc sets 

The renaming is also done in the `main` branch (which is for future releases). I have not removed the OSS pages from the `main` branch as this will happen automatically when @michaelklishin removes these pages from OSS (and I then copy in the OSS content into the Tanzu doc set for a future release) and the [redirects](https://app.zenhub.com/workspaces/opportunities-609b946a430cbb0017f18b9a/issues/rabbitmq/opportunities/206) are in place.

**Comment by DigitalBlasco** [comment]
Perfect, thank you @pstack2021
