### ISSUE TITLE
Slack self-invite app is no longer available, no new official home for the IRC channel

### ISSUE THREAD

**Issue by swantzter** [rabbitmq/rabbitmq-website#1569]
I was looking at https://www.rabbitmq.com/contact.html and was trying to join the IRC channel, and it says freenode which is dead, have you moved over to Libera.Chat or OFTC or something?
As an alternative I tried to join the Slack, but the linked https://rabbitmq-slack.herokuapp.com/ just gives a blank "application error" page (the end of Heroku free-tier?)

Is there a way these could be updated, and what would be the right info?

**Comment by michaelklishin** [comment]
I don't know where the IRC channel has moved, if anywhere at all. We can set one up next week.

As for the self-invite app on Heroku, both Slack and that app were set up by someone outside of VMware so we will have to look into how to transfer that account so that it can either use a paid tier or move to a different service.

**Comment by michaelklishin** [comment]
@swantzter we would be happy to move our IRC to Libera Chat. Do you know how we can get administrative privileges for `#rabbitmq` there?

**Comment by swantzter** [comment]
@michaelklishin I do! (well I'm biased as Libera Chat staff)
Just drop us an email, with the contents listed at https://libera.chat/chanreg/#project-registration to the address listed at the same place, we'll get back to do a quick verification and then dish out channel control

**Comment by michaelklishin** [comment]
@swantzter an org registration/claim email deployed! 😄

**Comment by michaelklishin** [comment]
Identifying myself as the person in an email thread with Libera staff :) `libera-5185brjnab15`

**Comment by michaelklishin** [comment]
Slack self-invite app is now back thanks to @gmr who has generously bumped it to a paid Heroku plan.
