### ISSUE TITLE
Document the `/metrics/detailed` endpoint in prometheus plugin

### ISSUE THREAD

**Issue by iliakur** [rabbitmq/rabbitmq-website#1579]
There is already [a good writeup](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_prometheus/metrics-detailed.md) of this endpoint, it's just not in the official docs :)

I'd be willing to make a PR to do this, opening the issue just in case there was a reason that this endpoint is not documented.

Thanks in advance.

**Comment by lukebakken** [comment]
We would appreciate it, thanks.

**Comment by michaelklishin** [comment]
No particular reason, it's just slipped through the cracks.
