### ISSUE TITLE
Oauth wildcard test url is broken

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [rabbitmq/rabbitmq-website#1601]
https://www.rabbitmq.com/oauth2.html

> See the [wildcard matching test suite](https://www.rabbitmq.com/test/wildcard_match_SUITE.erl) and [scopes test suite](https://www.rabbitmq.com/test/scope_SUITE.erl) for more examples.

Both links are broken, is there any replacement?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Would be also great to see a complete example of a (decoded) JWT token!

**Comment by michaelklishin** [comment]
There are [various examples available](https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/rabbitmq_auth_backend_oauth2/demo) and you can inspect decoded tokens using CLI tools of identity providers such as UAA (and I'm sure others).
