### ISSUE TITLE
Default Virtual Host and User section in access control doc lacks info for the case when definitions are imported in a blank node 

### ISSUE THREAD

**Issue by databu** [rabbitmq/rabbitmq-website#1608]
I'm using the RabbitMQ docker image and the default guest user for local testing with docker compose. However, after upgrading from some older version to 3.11 the default user and password failed to auth with an invalid credentials error.

I followed everything in the [access control doc ](https://www.rabbitmq.com/access-control.html) and other hints on the web, up to manually setting `default_user` and `default_pass` in `rabbitmq.conf`, but nothing worked.

Until I found this unimposing remark buried somewhere in the text in https://www.rabbitmq.com/definitions.html :

> The definitions in the file will not overwrite anything already in the broker. However, if a blank (uninitialised) node imports a definition file, it will not create the default virtual host and user.

We do import a definitions file to pre-define some queues, and so this was the reason. I've now fixed it by re-defining the default user and their permissions in our definitions file. 

My request is to add a remark about this in the [Default Virtual Host and User](https://www.rabbitmq.com/access-control.html#default-state) section in the access control doc.

**Comment by michaelklishin** [comment]
It's a fairly large doc site, we cannot put every "unimposing remark" into every guide.

RabbitMQ's core team suggestion to anyone who can to stop using the default user in production, leave alone
create a user with the default credentials when importing definitions.

**Comment by databu** [comment]
I called it "unimposing" as a criticism. 

As I mentioned, we're using it only in testing. But independent of that, it took me days to just find out what the problem was.
