### ISSUE TITLE
Wildcard documentation is incorrect

### ISSUE THREAD

**Issue by hitman-codehq** [rabbitmq/rabbitmq-website#1617]
Hello.

I was following the documentation on this page:

https://www.rabbitmq.com/tutorials/tutorial-five-python.html

As I wanted to subscribe to a topic using wildcards.  For example, the topic is /this/is/my/topic and I wanted to subscribe using /*/*/my/topic.  However, this did not work.  A colleague then suggested that I use /+/+/my/topic instead, and this worked!  This is using MQTT.

Is there a reason this is documented like it is?  I could not find any mention of using the + character on the RabbitMQ website and the documentation saying to use * is misleading.

Many thanks in advance!

**Comment by michaelklishin** [comment]
That tutorial does not use MQTT if you take a closer look. Wildcard routing syntax differs from protocol to protocol.
