### ISSUE TITLE
Clarify direct exchange description on page AMQP 0-9-1 Model Explained

### ISSUE THREAD

**Issue by MikePSQR** [rabbitmq/rabbitmq-website#1620]
https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-direct

The image shows 2 queues registered with the same routing key, but the description does not make it clear how that behaves:

"When a new message with routing key R arrives at the direct exchange, the exchange routes it to the queue if K = R"

The latter description does not help. it says:

"Direct exchanges are often used to distribute tasks between multiple workers (instances of the same application) in a round robin manner."

Looking at the image I would understand this as: if there are multiple queues bound to same routing key, they get messages in round robin manner. But the next sentence says that is not the case:

"When doing so, it is important to understand that, in AMQP 0-9-1, messages are load balanced between consumers and not between queues."

That sounds like this round robin manner applies to multiple consumers of the same queue, not to multiple queues with same routing key.

Can you please clarify what happens in the setup as shown in the picture?

**Comment by michaelklishin** [comment]
You are looking at a 15 year old text. Round robin distribution happens between consumers and it's been the case since at least 2010. We will remove the part that mentions round robin.

**Comment by MikePSQR** [comment]
great, also I would suggest: "... the exchange routes it to all queues for which K = R"

**Comment by MikePSQR** [comment]
Also, there are two headers with the same name "Message acknowledgements"
https://www.rabbitmq.com/tutorials/amqp-concepts.html#message-acknowledge
https://www.rabbitmq.com/tutorials/amqp-concepts.html#acknowledgements
