### ISSUE TITLE
Tutorials licensing question

### ISSUE THREAD

**Issue by deadtrickster** [rabbitmq/rabbitmq-website#163]
Firstly sorry for the noise.

No so long ago we've ported tutorials to Common Lisp (http://cl-rabbit.io/cl-bunny/tutorials/). And all this time I'm trying to figure out how to properly give attribution and all other licensing stuff. Could you please help me?

**Comment by michaelklishin** [comment]
The license is [Apache 2.0](https://github.com/rabbitmq/rabbitmq-website/blob/master/LICENSE), and license headers use XML/HTML/CSS comments. That's pretty much it. Stuff that's expected to go live soon should be submitted against the `live` branch.

**Comment by deadtrickster** [comment]
@michaelklishin thank you for the answer

Do you think you can accept lisp tutorials here? I mean my cl-bunny works but I'm not sure it is widely used :-)

**Comment by michaelklishin** [comment]
Lets start by moving your CL tutorials to [rabbitmq-tutorials](https://github.com/rabbitmq/rabbitmq-tutorials). We produce guides for more popular clients, that's true, but only because our team is small and documentation requires maintenance, too. We are not against having tutorials for Erlang, Clojure, Haskell, CL in the future.

**Comment by deadtrickster** [comment]
Ok, rabbitmq-tutorials contains only code right? Also I see travis.yml what you test here?

**Comment by michaelklishin** [comment]
We (try to) test interoperability between tutorials in various languages. That's actually a lot of pain and I doubt we've been adding recent ports to that test suite. It's also timing-sensitive. So manually running your examples against, say, Python or Ruby should be enough.

`rabbitmq-tutorials` only has code.

**Comment by deadtrickster** [comment]
Michael, thank you for amazingly quick responses
Hopefully I'll contribute something useful soon.
