### ISSUE TITLE
Dark Mode for the website

### ISSUE THREAD

**Issue by bulldog98** [rabbitmq/rabbitmq-website#1637]
### Is your feature request related to a problem? Please describe.

If the system is in dark mode, the bright white website for rabbitmq is quite the jarring contrast

### Describe the solution you'd like

Having a dark mode/theme that is automatically enabled depending on the system prefererence

**Comment by michaelklishin** [comment]
Management UI [supports themes](https://github.com/rabbitmq/rabbitmq-management-themes), I don't think our team has the cycles to work on Dark mode for the UI but any user can develop one.

**Comment by michaelklishin** [comment]
I suspect various browser plugins can help. Or, if someone really feels the need for an alternative set of stylesheets for rabbitmq.com, this repo is open source. A pull request would be considered.
