### ISSUE TITLE
rabbitmq debian repo support for ppc64le

### ISSUE THREAD

**Issue by mikehollinger** [rabbitmq/rabbitmq-website#166]
When attempting to install via apt-get on a ppc64le system (i.e. an OpenPower / POWER8 server), the apt-get install fails because the rabbitmq repo doesn't claim support for ppc64le (i.e. http://www.rabbitmq.com/debian/dists/testing/InRelease lists many things, but not that). 

Manually downloading the debian package (e.g. http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.1/rabbitmq-server_3.6.1-1_all.deb) works like a champ, assuming erlang is present on the machine.

Can you add ppc64le to your supported architectures in the repo?

**Comment by michaelklishin** [comment]
Moved to https://github.com/rabbitmq/rabbitmq-server/issues/738.
