### ISSUE TITLE
Update the "Sending doesn't work!" section of the first tutorial

### ISSUE THREAD

**Issue by pedrowindisch** [rabbitmq/rabbitmq-website#1677]
### Describe the bug

The first tutorial has a section titled "Sending doesn't work!" with advices regarding some possible errors when first using RabbitMQ. The section states that "Maybe the broker was started without enough free disk space (by default it needs **at least 200 MB free**) and [...]".

However, according to the [docs](https://www.rabbitmq.com/configure.html#config-items), RabbitMQ actually needs 50 MB of free disk space at a minimum (not 200 MB as the section states).

### Reproduction steps

.

### Expected behavior

.

### Additional context

The [.NET tutorial](https://www.rabbitmq.com/tutorials/tutorial-one-dotnet.html) is correct.

If possible, I'd like to work on this issue.

**Comment by michaelklishin** [comment]
It doesn't really matter what the absolute minimum is (to not trigger a disk alarm). The point is that the user should pay attention to what partition the data directory is on, and asking for at least 200 MiB is perfectly fine. 

A node that just has enough to not go into resource alarmed state won't be of much use in practice. Most workloads, in fact, nearly all of them, require at least some disk space. 

As of 4.0, transient entities (e.g. transient queues) will be a thing of the past, so if anything, I think the low free disk space watermark will be revisited higher, for example, to 200 MiB.

**Comment by pedrowindisch** [comment]
Oh, right, thanks for explaining. I just found it strange and conflicting that the .NET tutorial states 50 MB as the default, while the other languages tutorials say the default is 200 MB.

**Comment by michaelklishin** [comment]
The .NET tutorial may be the oldest one there is (or at least the second oldest, after the Java one).

I will take a look.
