### ISSUE TITLE
Add versioning at the minor level to OSS RabbitMQ doc set going forward

### ISSUE THREAD

**Issue by pstack2021** [rabbitmq/rabbitmq-website#1692]
### Is your feature request related to a problem? Please describe.

**Problems:**

1. 1 public version of OSS RabbitMQ docs live on production: https://www.rabbitmq.com/documentation.html yet we have many customers using previous versions of OSS RabbitMQ (back to 3.6 and up to 3.11 and onwards). We have no way of giving users the docs for the version they are using. Also, if we introduced versioning, we could do some analytics on what actual OSS RabbitMQ version users are on based on the OSS RabbitMQ doc version they access. Perhaps, include links to the list of OSS RabbitMQ doc versions in the Management UI and if a user selected a specific version of the docs, it would give us a strong indication of the version of the RabbitMQ product they are using. 

2. Still introducing features into minor RabbitMQ versions but we are not specifying in docs what version these features apply to which leads to a situation like this: A user was asking about [per-object metrics functionality documented in the docs](https://www.rabbitmq.com/prometheus.html#metric-aggregation), the user was getting no results while using this functionality in the product - why? the user was using 3.8.5 and it was introduced in a later 3.8.x (3.8.15??) version - Documentation is not specifying any of these changes. **Link to conversation with this issue:** https://discord.com/channels/1092487794984755311/1092487794984755314/1131161059844161567

3. Issue with pulling in 1 public version of OSS RabbitMQ docs into the Commercial VMware RMQ doc sets when commercial releases are not based off of the latest RMQ packages and documentation. Right now, the latest OSS RabbitMQ version is on 3.12.x. VMware RabbitMQ 1.4 offerings are based off 3.11.18 hence @pstack2021 can't copy the OSS RabbitMQ docs from the `live` branch: https://github.com/rabbitmq/rabbitmq-website into the VMware RabbitMQ 1.4 docs. Instead we are currently using a 2nd `v3.11.x` branch https://github.com/rabbitmq/rabbitmq-website/tree/v3.11.x to copy OSS RabbitMQ docs into 1.4 docs when needed. Also the extra work now of daily checking doc updates that go into the `live` branch that are not 3.12 specific, for example: updates for bug fixes now make it into both the `v3.11.x` and `live` branches.

4. OSS RabbitMQ doc pages longer (and as a result harder to read - make it harder to find what you are looking for) because we are covering all information for a piece of functionality for every version on the same page... Text like "until this version this was true" then "in that version, that is true", and so on - doc versioning would eliminate this and make content shorter/concise/just document what is needed for the version you are on. 

**Why we can't/are not doing this right now?**
- Are the tools we are using to publish OSS RabbitMQ documentation stopping us versioning the docs? 

### Describe the solution you'd like

**Solution:**
Introduce versioning at the minor level in OSS RabbitMQ docs (i.e. X.X - which will cover any maintenance level X.X.x updates)

I don't think features are introduced at the maintenance level anyway just bug fixes right?? but if we did introduce some functionality in a maintenance release then we should include a note/label/some identifier stating something like: _Starting in RabbitMQ version 3.x.x,, a new "blah" feature is included.", see the [Audit Logger package documentation](https://docs.vmware.com/en/VMware-RabbitMQ-for-Kubernetes/1.4/rmq/GUID-installation.html#install-tanzu-rabbitmq-audit-logger-package) which was introduced in VMware RabbitMQ for K8s v1.4.2 for an example of this.

If versioning is introduced in OSS RabbitMQ docs, could we have docs and code in the same repo - PR to update the code AND docs at the same time, helping to keep them in sync always and then push them to production together. 

**When to do this:**
Introduce a new versioned doc set for RabbitMQ 4.0. Keep the current documentation as it is for version 3.X. Then really start introducing versioning at the minor level in version 4.1.

**Comment by mkuratczyk** [comment]
We add functionality in patch releases, probably too often in fact. But even if we didn't, a bugfix could require some documentation changes. Either way, I think the proposal is good - each minor has its own documentation and if needed, things that changed in a patch release are explicitly mentioned.

**Comment by pstack2021** [comment]
Thanks @mkuratczyk for your feedback.

@michaelklishin @HowardTwine @DigitalBlasco @edbyford @MirahImage please add your thoughts here on this proposal. I will then organise a meeting with all people here to discuss further when I return from PTO on the week of the 14th of August, thanks.

**Comment by pstack2021** [comment]
Meeting minutes from **Discuss adding versioning at the minor level to OSS RabbitMQ doc set going forward** held on 22/08/2023 @12 GMT
Attendees: @MirahImage @HowardTwine @mkuratczyk @michaelklishin @pstack2021 

### Meeting Outcomes

1. Agreement from Product Management and all meeting attendees that versioning at the minor level is needed in OSS RMQ doc site. 
2. We will not go back with doc versioning, forward only, this solution is definitely needed for 4.0, work needs to happen now to make this happen. RabbitMQ 3.13 is coming out before 4.0. Maybe, we park what we have in 3.13 as the 3.X version (with a blurb explaining what 3.X docs include) and then have a new 4.0 minor version of docs, 4.1, 4.2, etc etc in the future
3. Continue to use the current "homegrown" website generator being used.
4. Continue to use [hush-house](https://github.com/concourse/hush-house)
5. @michaelklishin to spend 1 day per week starting now and we will reconvene in a month or so (around 26th of September).  

### Next steps to implement:

1. @michaelklishin to open separate issue/s for the technical work items - @michaelklishin please link these new issues to this main issue,

- use subdomains or prefixes
- Add a version switcher
- Possibly start with deploying with multiple doc versions 
- Test with the management UI which has documentation link on the footer: a) deploy multiple doc versions b) add a link in future RMQ patch releases to point to the specific doc version from the main documentation link on the Management UI. 
 - HTTP API documentation is clearly versioned accessible from a link on the Management UI, with versioning now being implemented in the OSS RabbitMQ docs, we could now move this documentation to the main RMQ doc website which will have versioning also (addressing a problem which has been around for a long time). We could use Swagger or another alternative to modernise HTTP API documentation. 
 
2. @mkuratczyk to open an issue to evaluate docsy.dev to see how much work it would be to move our current docs and what the workflow would be if we used it.

### Other technical notes

- Biggest issue is that a "homegrown" website generator is used works well for 1 edition but not multiple editions, it assumes we only document the latest. If you want to document anything else, then a sub-domain is needed. That situation has resulted in more issues when the switch to deploy into Cloudflare workers happened. **A solution to this might be use** Cloudflare workers OR deploy into sub domains (maybe have a sub-domain per version). If you don't specify a version, it takes you to the latest version??

Another alternative, use a version selector that uses path prefixes, we would need to be careful using them, would need to have all doc editions in the same repo (multiple domains and multiple branches). An issue with multiple branches. With multiple branches,  we will have to back-port doc updates to multiple series (in practice we support 3 series right now: 3.10, 3.11, and 3.12, 3.13 coming soon), it is doable as we are doing it in code right now. Must have a process in place to ensure back porting happens correctly and consistently. 
Possible tools to manage back porting/keeping docs up to date: [Gitbook](https://docs.gitbook.com/) and [docsy](https://www.docsy.dev/docs/adding-content/versioning/). 

- Installation to move it: Runway (SFO instance on Runway is functional), @michaelklishin and @MirahImage to work through this. 
 - Create doc version branches
 - Setup Mergify so back porting of doc updates are automated. Approach back porting in the docs, the same way that is done in the RMQ code.

**Comment by pstack2021** [comment]
[oss-rmq-doc-versioning](https://vmware.slack.com/archives/C05NY0FDU4T) slack channel tracking the progress of this project.

**Comment by pstack2021** [comment]
[RabbitMQ Documentation Improvements Proposal ](https://docs.google.com/document/d/1aGMcUx3PgFwloOwcmAkslkbFg31hh578u595FizZF5E/edit#heading=h.1hoqwqtp78tu)

**Comment by pstack2021** [comment]
Follow on meeting 1 - held on 28/09/2023 @12 GMT 
Attendees: @MirahImage @DigitalBlasco @mkuratczyk @dumbbell @pstack2021

**Meetings Minutes:** 
The details below are also added to the[ RabbitMQ Documentation Improvements Proposal document where applicable. ](https://docs.google.com/document/d/1aGMcUx3PgFwloOwcmAkslkbFg31hh578u595FizZF5E/edit#heading=h.1hoqwqtp78tu)

**Outcome**
Agreement to move forward with the [Docsy](https://docsy.dev/) as the framework for maintaining OSS RabbitMQ documentation in the future. As a result, the "homegrown" generator will not be used going forward. Hugo is the website generator used with [Docsy](https://docsy.dev/).

**More items still to be worked** 

1. Are we going with 1 Deployment with versions and folders OR multiple deployments with separate versions??

**Actions:** 

1. @mkuratczyk to do some further investigation around versioning.

2. @mkuratczyk: to setup a new domain, move OSS RMQ docs to [Docsy](https://docsy.dev/) and create a new table of contents from these, @pstack2021, product management, and engineering to review and provide feedback on the new TOC

3.  **This action needs an owner**: How difficult would it be to keep the [current OSS RMQ doc website](https://www.rabbitmq.com/documentation.html) with all 3.x content under Docsy as a 3.x folder. For all 3.x documentation, we would continue to maintain the same URLs, the same files, and structure (no TOC). If we can do this, then we will avoid maintaining 2 separate workflows: 3.x and 4.0. We could have 1 workflow/deployment that will hold both 3.x and 4.0 with the 3.x documentation formatted the same way it is now on the Docsy page whereas the 4.0 docs will take the Docsy formatting, new TOC and structure etc

**Comment by dumbbell** [comment]
Minutes from the 2023-10-27 meeting:

##  Choosing a tool

* Docusaurus looks better
* Backporting workflow is a concern though: we have to be clear that we are working with folders, not Git branches

## How to proceed?

1. New branch in the rabbitmq-website repository to work on the switch
2. Switch existing website to Docusaurus
3. Use GitHub Actions + Cloudflare to deploy to a temporary domain
4. Deploy to www.rabbitmq.com if it works

@dumbbell will work the switch to Docusaurus, @mkuratczyk to help with the automated deployment to Cloudflare.

**Comment by pstack2021** [comment]
To follow the latest progress of the New OSS RMQ doc site, review all details on:

- the # oss-rmq-doc-versioning slack channel
- [OSS RabbitMQ Documentation Improvements Proposal - Lets version the docs google doc](https://docs.google.com/document/d/1aGMcUx3PgFwloOwcmAkslkbFg31hh578u595FizZF5E/edit#heading=h.1hoqwqtp78tu)

**Comment by pstack2021** [comment]
Tasks that need to be done to officially go live with the new site:

- [Paula to flesh out [Introduction](https://www.google.com/url?q=https://rabbitmq-website.pages.dev/docs/documentation&sa=D&source=calendar&ust=1706993313137358&usg=AOvVaw2x6B0ynBRL3YEJs9jBNI9i) page, explain what the drop down menus are, how to navigate around docs] 
- 

a) Paula to flesh out [Introduction](https://www.google.com/url?q=https://rabbitmq-website.pages.dev/docs/documentation&sa=D&source=calendar&ust=1706993313137358&usg=AOvVaw2x6B0ynBRL3YEJs9jBNI9i) page, explain what the drop down menus are, how to navigate around docs
b) Implement TOC updates in source files. Paula or JSP to complete.
c) Paula to write H1 container topics based on the TOC we are going ahead for initial release. 
d) Pull the latest updates from the "live" branch: [https://github.com/rabbitmq/rabbitmq-website](https://www.google.com/url?q=https://github.com/rabbitmq/rabbitmq-website&sa=D&source=calendar&ust=1706993313137358&usg=AOvVaw0iMfxZ4oJysplX8AfURCmd) into the docusaurus site: [https://github.com/rabbitmq/rabbitmq-website/tree/switch-to-docusaurus](https://www.google.com/url?q=https://github.com/rabbitmq/rabbitmq-website/tree/switch-to-docusaurus&sa=D&source=calendar&ust=1706993313137358&usg=AOvVaw3H2-ReojOJ85Z0c4N-3L9V) and ensure all is working when we go live  with the new site - JSP to complete? 
e) Check links etc are all working
f) What tasks must be completed on other parts of the new site (i.e. non doc tasks) such as "Blogs" etc
g) Other tasks - what are they?

- [ ]

**Comment by dumbbell** [comment]
Implemented in #1783.
