### ISSUE TITLE
Add RabbitMQ Ballerina lang client to Client Libraries section

### ISSUE THREAD

**Issue by aashikam** [rabbitmq/rabbitmq-website#1704]
### Is your feature request related to a problem? Please describe.

[Ballerina](https://ballerina.io/) lang provides support for RabbitMQ. It would be great if you could mention the Ballerina client for RabbitMQ in https://www.rabbitmq.com/devtools.html.

**References**
Ballerina:
Site: https://ballerina.io/
Central: https://central.ballerina.io/

RabbitMQ client:
Package: ballerinax/rabbitmq
Latest: https://central.ballerina.io/ballerinax/rabbitmq/latest
Source: https://github.com/ballerina-platform/module-ballerinax-rabbitmq

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by michaelklishin** [comment]
I'm afraid we cannot assess the quality of this library right now. I don't see any [Publisher confirms](https://rabbitmq.com/publishers.html#data-safety) support mentioned in the docs, for example.

You are welcome to submit a PR that adds Ballerina to that page, the website is open source.
