### ISSUE TITLE
Per Message TTL Caveats Documentation Update

### ISSUE THREAD

**Issue by ramikhafagi96** [rabbitmq/rabbitmq-website#1788]
## Problem Definition
In [Time-To-Live and Expiration Caveats Section](https://www.rabbitmq.com/ttl.html#per-message-ttl-caveats), It is mentioned that `Only when expired messages reach the head of a queue will they actually be discarded (or dead-lettered).` which is not true now. What actually happens is when the message TTL expires it gets discarded and dead-lettered even if it was not at the head of the queue. So, I think this was an old behavior given that it was written 6 years ago and it hasn't been updated since then.

## Impact
Because of this out-dated documentation we took a design choice to implement delayed messages by creating many queues with different TTL on the queue itself and it made our design very complicated while it could've been much simpler if we used TTL on messages

## Code Example

You can find below code example for showing that the mentioned behavior is not valid. The code example creates two queues the first one messages with expiration property are enqueued in it and when the TTL expires it gets dead-lettered to another queue and there's a running consumer that consumes from the dead-letter queue.

```python3
# publisher
import pika

# Connection parameters
url = "amqp://guest:guest@localhost:5672/%2F"
params = pika.URLParameters(url)

# Establish a connection with RabbitMQ server
connection = pika.BlockingConnection(params)
channel = connection.channel()

# Declare an exchange
exchange_name = "my-exchange"
channel.exchange_declare(exchange=exchange_name, exchange_type='direct')

# Declare queues
orders_queue = "orders-queue"
delay_queue = "delay-orders-queue"

channel.queue_declare(queue=orders_queue)
channel.queue_declare(queue=delay_queue, arguments={
    "x-dead-letter-exchange": exchange_name,
    "x-dead-letter-routing-key": "orders"
})

# Bind queues to the exchange
channel.queue_bind(queue=orders_queue, exchange=exchange_name, routing_key="orders")
channel.queue_bind(queue=delay_queue, exchange=exchange_name, routing_key="delayed-orders")

# Publish messages
message_body_no_ttl = 'delayed-message-no-ttl'
channel.basic_publish(exchange=exchange_name,
                      routing_key="delayed-orders",
                      body=message_body_no_ttl,
                      properties=pika.BasicProperties(content_type='text/plain'))

message_body_longer_ttl = "delayed-message-longer-ttl"
channel.basic_publish(exchange=exchange_name,
                      routing_key="delayed-orders",
                      body=message_body_longer_ttl,
                      properties=pika.BasicProperties(content_type='text/plain', expiration="10000"))

message_body_shorter_ttl = 'delayed-message-shorter-ttl'
channel.basic_publish(exchange=exchange_name,
                      routing_key="delayed-orders",
                      body=message_body_shorter_ttl,
                      properties=pika.BasicProperties(content_type='text/plain', expiration='5000'))

# Close the connection
connection.close()
```

```python3
# consumer
import pika

def on_message(channel, method_frame, header_frame, body):
    """Callback function to process the message."""
    print(f"Received message: {body.decode()}")
    # Acknowledge the message
    channel.basic_ack(delivery_tag=method_frame.delivery_tag)

# Connection parameters
url = "amqp://guest:guest@localhost:5672/%2F"
params = pika.URLParameters(url)

# Establish a connection with RabbitMQ server
connection = pika.BlockingConnection(params)
channel = connection.channel()

# Declare the queue (make sure it's the same name as the producer's queue)
queue_name = 'orders-queue'
channel.queue_declare(queue=queue_name)

# Start consuming messages from the queue
channel.basic_consume(queue=queue_name, on_message_callback=on_message, auto_ack=False)

print("Starting Consuming")
try:
    channel.start_consuming()
except KeyboardInterrupt:
    channel.stop_consuming()
except Exception as e:
    print(f"Error: {e}")
    channel.stop_consuming()

# Close the connection
connection.close()

```

### Describe the solution you'd like

I suggest that this should be updated because it can lead to bad design choices

**Comment by michaelklishin** [comment]
This is still just as true for classic queues.

**Comment by ramikhafagi96** [comment]
But in my code example that's not the case, the queue already had an unconsumed message at the head and published messages with ttl when they got expired they were dead-lettered despite having a message with no expiration at the head of the queue. Doesn't that contradict with the documentation?

**Comment by michaelklishin** [comment]
@ramikhafagi96 I have updated my comment above. You are making an assumption that everyone uses TTL for scheduled dead lettering. That's not at all the case.
