### ISSUE TITLE
https://www.rabbitmq.com/news.atom is missing

### ISSUE THREAD

**Issue by robi-wan** [rabbitmq/rabbitmq-website#1814]
### Describe the bug

I subscribed to https://www.rabbitmq.com/news.atom via an RSS reader to get informed about the newest RabbitMQ updates.
With the launch of new website this feed seems to be gone.
What is the new recommended way of getting the news about updates?
I really liked the RSS approach.

### Reproduction steps

1. Enter https://www.rabbitmq.com/news.atom in a browser.
2. "Page Not Found" is the result (HTTP code 404 in the browser developer tools)

### Expected behavior

An RSS feed compatible result is returned.

**Comment by michaelklishin** [comment]
[Here's why](https://docusaurus.io/docs/blog#feed) I think that an atom feed for the blog should be readily available or at least easy to set up.

But the future of the News page is highly uncertain. Watching GitHub releases, or just checking the change log page once a month, are two by far more common options.
