### ISSUE TITLE
Headings on right nav look strange

### ISSUE THREAD

**Issue by edbyford** [rabbitmq/rabbitmq-website#1837]
### Describe the bug

![image](https://github.com/rabbitmq/rabbitmq-website/assets/5754823/c51191e7-7698-4497-98c5-5832d60d585b)

### Reproduction steps

1. Go to /versions.html
2. View right hand nav bar

### Expected behavior

Without the $ symbols etc :)

**Comment by lukebakken** [comment]
I think this has been addressed ... `/versions.html` now redirects to this page:

https://www.rabbitmq.com/release-information

...which appears correctly.
