### ISSUE TITLE
Please update the feature flags for 3.13.0

### ISSUE THREAD

**Issue by bodograumann** [rabbitmq/rabbitmq-website#1842]
### Is your feature request related to a problem? Please describe.

We updated to rabbitmq 3.13 and the documentation looked like there are no new feature flags to enable.
Turns out there are, but they are missing from the documentation.

### Describe the solution you'd like

The following flags need to be added afaics:
- detailed_queues_endpoint
- khepri_db
- message_containers
- stream_update_config_command

Also usually it is recommended to enable all of them after the upgrade, but `khepri_db` seems different according to the 3.13 release announcement. That should probably highlighted in the docs as well.

**Comment by michaelklishin** [comment]
@bodograumann as the docs now say,

```
rabbitmqctl enable_feature_flag all
```

will only enable stable feature flags, and `khepri_db` is currently an experimental one.

**Comment by michaelklishin** [comment]
@mohag you are welcome to contribute one. This is open source software after all.
