### ISSUE TITLE
Shovel URI examples are incorrect

### ISSUE THREAD

**Issue by womblep** [rabbitmq/rabbitmq-website#1931]
### Describe the bug

One of the example URI formats in the shovel-management plugin are wrong and wont work on 3.13.
The https://www.rabbitmq.com/docs/uri-query-parameters page is also wrong in it's example

### Reproduction steps

The last example on the shovel management plugin URI example page is amqps://server-name?cacertfile=/path/to/cacert.pem&certfile=/path/to/cert.pem&keyfile=/path/to/key.pem&verify=verify_peer&**fail_if_no_peer_cert=true**&auth_mechanism=external

The uri query parameters documentation page is also wrong with the example for advanced.config
{amqp_client, [
    {ssl_options, [
        {cacertfile, "path-to-ca-certificate"},
        {certfile, "path-to-certificate"},
        {keyfile, "path-to-keyfile"},
        {verify, verify_peer},
        **{fail_if_no_peer_cert, true}**
    ]}
]}

fail_if_no_peer_cert is not accepted anymore with Erlang 26 and will fail with a not obvious error (for non erlang users like myself)

### Expected behavior

Examples should work :-)

**Comment by lukebakken** [comment]
Anyone can open a PR for the documentation, you don't even need to file an issue first. Here is the relevant page:

https://github.com/rabbitmq/rabbitmq-website/blob/main/docs/uri-query-parameters.md

**Comment by womblep** [comment]
@lukebakken no problem I can do that one. 
I have no idea how to start with the shovel-management plugin

**Comment by womblep** [comment]
PR #1933 added

**Comment by lukebakken** [comment]
Fixed by #1933

**Comment by womblep** [comment]
@lukebakken I have also put a PR in rabbitmq-server for the shovel-management PR #11318
