### ISSUE TITLE
Documentation states wrong Erlang version for Windows installation

### ISSUE THREAD

**Issue by sverker84** [rabbitmq/rabbitmq-website#1938]
### Describe the bug

The documentation at https://www.rabbitmq.com/docs/install-windows#dependencies says the latest supported Erland version is 25.3, but starting with 3.12 of RabbitMQ, the latest supported version is 26.x.
With 3.13, Erlang 25.x isn't supported at all.

The documentation should be updated to reflect this. Perhaps the part about the latest supported version should be removed entirely and only link to the Erlang Version Requirements page at https://www.rabbitmq.com/docs/which-erlang

### Reproduction steps

1. Download Erlang 25.3 and install on Windows
2. Try to install RabbitMQ 3.13 on Windows - it will say Erlang is the wrong version
...

### Expected behavior

I should've downloaded the correct version of Erlang

**Comment by michaelklishin** [comment]
Fixed in cfbeafce6fbb1d9684e6282ac8a73ae5c18ac948.
