### ISSUE TITLE
Java tutorial 1 has a broken external link

### ISSUE THREAD

**Issue by Pushkar-Mahajan4** [rabbitmq/rabbitmq-website#1975]
### Describe the bug

While following the tutorial for [Java](https://www.rabbitmq.com/tutorials/tutorial-one-java) I ran into an error while sending message on the queue. The webpage asks to check [configuration file documentation](https://www.rabbitmq.com/configure#config-items). Which returns a 404 error
![image](https://github.com/user-attachments/assets/83071076-0fc6-4dd5-bd3e-74e6505a0b28)

### Reproduction steps

1. Go to [java tutorial](https://www.rabbitmq.com/tutorials/tutorial-one-java)
2. Scroll down to : [Sending doesn't work!](https://www.rabbitmq.com/tutorials/tutorial-one-java#sending-doesnt-work)
3. Click on [configuration file documentation](https://www.rabbitmq.com/configure#config-items)
...

### Expected behavior

Display the configuration file documentation page.

**Comment by michaelklishin** [comment]
Thank you for providing these details.
