### ISSUE TITLE
The Grafana dashboard link is broken

### ISSUE THREAD

**Issue by yotamN** [rabbitmq/rabbitmq-website#1999]
### Describe the bug

The link to the Grafana dashboard template is broken, not sure what link is the correct one

### Reproduction steps

1. Open the Prometheus page (https://www.rabbitmq.com/docs/prometheus)
2. Click on [prebuilt set of Grafana dashboards](https://grafana.com/rabbitmq)
3. See 404

### Expected behavior

Link to the proper Grafana dashboard template

**Comment by michaelklishin** [comment]
I'm afraid It Works on My Machine™:
![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/3a6908bc-92a1-4f29-843c-bcd47a3a62ff)

**Comment by yotamN** [comment]
Are you logged-in to Grafana by any chance? I still get 404 and I assume it's a permissions problem

**Comment by michaelklishin** [comment]
@yotamN I'm not. I can access https://grafana.com/orgs/rabbitmq in a private browsing window just fine.

The dashboards are open source and have always been. They were last updated in Dec 2023, so if this was a permissions problem I'd expect it to be reported many times by now.
