### ISSUE TITLE
Link to private Youtube video

### ISSUE THREAD

**Issue by rauno56** [rabbitmq/rabbitmq-website#2014]
### Describe the bug

[3.13 announcement blog post](https://github.com/rabbitmq/rabbitmq-website/blob/main/blog/2024-03-11-rabbitmq-3.13.0-announcement/index.md) contains a link to a [private Youtube video](https://www.youtube.com/watch?v=whVqpgvep90).

### Reproduction steps

..

### Expected behavior

..

**Comment by michaelklishin** [comment]
I have no idea why that RabbitMQ Summit video was taken private. I cannot find another version so all we can do is to simply link to the Khepri repository.

**Comment by johanrhodin** [comment]
@michaelklishin If I understand it correctly the video is not from RabbitMQ Summit but from Code beam 2023. Anyway I'll check with them so that the video can return.

**Comment by michaelklishin** [comment]
@johanrhodin could be. It was a recent talk on Khepri by @the-mikedavis, I know that much.
