### ISSUE TITLE
Invalid ATOM news feed

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-website#21]
See the W3C report:
http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.rabbitmq.com%2Fnews.atom

Reported by Aaron Kondziela <aaron@aaronkondziela.com> on the mailing-list:
https://groups.google.com/d/topic/rabbitmq-users/RuNYBYRy5EI/discussion

**Comment by asbjornu** [comment]
This was fixed in #121.
