### ISSUE TITLE
Tutorial 5: `*` segments in routing keys are not rendered on SVG images

### ISSUE THREAD

**Issue by mPandaer** [rabbitmq/rabbitmq-website#2150]
### Describe the bug

My environment: Chrome 131.0.6778.205
When browsing the "Topic exchange" section of the tutorial at https://www.rabbitmq.com/tutorials/tutorial-five-java, the image and text descriptions do not match. Specifically, the image shows `.orange.` while the text describes `*.orange.*`.

![image](https://github.com/user-attachments/assets/3f4be21d-3fe2-41af-8d04-d24e5f830d19)

### Reproduction steps

1. Open the link. https://www.rabbitmq.com/tutorials/tutorial-five-java
2. Find the corresponding section "Topic exchange."

### Expected behavior

The image and the text content match

**Comment by lukebakken** [comment]
Thanks for the report. This is fixed by #2151

**Comment by lukebakken** [comment]
Force-refresh, and 🥳 
![image](https://github.com/user-attachments/assets/3ae13941-e599-45ba-b24c-b50447ad4c8c)
