### ISSUE TITLE
Sudo is required on osx homebrew

### ISSUE THREAD

**Issue by morenoh149** [rabbitmq/rabbitmq-website#227]
This line should change https://github.com/rabbitmq/rabbitmq-website/blob/d1f5f4a5592d303e5e959dc07e9c50b6668941de/site/install-homebrew.xml#L52

unless I'm mistaken rabbitmq-server must be run as sudo as many files within `/usr/local/var` are utilized by rabbitmq.

The exact error:
```shell
$ rabbitmq-server
/usr/local/sbin/rabbitmq-server: line 49: /usr/local/var/lib/rabbitmq/mnesia/rabbit@localhost.pid: Permission denied
Failed to write pid file: /usr/local/var/lib/rabbitmq/mnesia/rabbit@localhost.pid
```

chowning this file leads to a crash dump
```shell
rabbitmq-server                                                 
{error_logger,{{2016,6,29},{14,41,9}},"Error when reading /Users/harrymoreno/.erlang.cookie: eacces",[]}
```
chowning that complains
```
BOOT FAILED
===========

Error description:
   {error,{cannot_log_to_file,"/usr/local/var/log/rabbitmq/rabbit@localhost.log",
                              {error,eacces}}}
```
chowning that
```
BOOT FAILED
===========

Error description:
   {error,{could_not_write_file,"/usr/local/var/lib/rabbitmq/mnesia/rabbit@localhost/cluster_nodes.config",
                                eacces}}
```

Also documented elsewhere http://docs.celeryproject.org/en/latest/getting-started/brokers/rabbitmq.html#starting-stopping-the-rabbitmq-server I don't think it's a coincidence.

cc @alexahn @evanrs

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.

**Comment by michaelklishin** [comment]
RabbitMQ CLI tools and `rabbitmq-server` do not require `sudo`. Locations of [just about everything](http://www.rabbitmq.com/relocate.html) (except for the Erlang cookie in most cases) can be overridden. I never use `sudo` with `rabbitmq-server` or any of the CLI tools, for example.

**Comment by michaelklishin** [comment]
RabbitMQ will attempt to create directories recursively up to `/usr/local/var/log/`. Everything under Homebrew Cellar is supposed to be owned by your own user, as far as I know (at least how I use it).

**Comment by morenoh149** [comment]
So I have homebrew incorrectly configured? what should be chowned by the non root user? `/usr/local/var/`?

**Comment by michaelklishin** [comment]
Homebrew's data directories, I don't know if it's `/usr/local/var` or something else by default. Note that Homebrew isn't necessarily installed as `/usr/local`, too.

**Comment by kekkokk** [comment]
I have the same problem.
I need to run rabbitmq as non root user but in the first place I got:

>user$ /usr/local/sbin/rabbitmq-server
> /usr/local/sbin/rabbitmq-server: line 51: /usr/local/var/lib/rabbitmq/mnesia/rabbit@localhost.pid: Permission denied
> Failed to write pid file: /usr/local/var/lib/rabbitmq/mnesia/rabbit@localhost.pid

then I chowned /usr/local/var/lib/rabbitmq as my user and I got:

> 2017-11-09 14:43:55 Error when reading /Users/user/.erlang.cookie: eacces

note that I have a basic homebrew installation and I have changed nothing

**Comment by michaelklishin** [comment]
This is not a Homebrew support forum. [Erlang cookie file requirements](http://www.rabbitmq.com/cli.html) are documented. You can remove the file and RabbitMQ (well, the runtime) will create it on start if it doesn't exist.
