### ISSUE TITLE
Javascript Tutorial #1: new Buffer is deprecated as of Node v6.0.0

### ISSUE THREAD

**Issue by Robinnnnn** [rabbitmq/rabbitmq-website#230]
Node has [deprecated](https://nodejs.org/api/buffer.html#buffer_class_buffer) the use of `new Buffer()` as of v6.0.0 and has assigned it a stability score of 0. The Javascript tutorial should utilize [`Buffer.from`](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_str_encoding) instead, which was introduced in v5.10.0.

Specifically, the [message sending example](https://www.rabbitmq.com/tutorials/tutorial-one-javascript.html) with this line:

`ch.sendToQueue(q, new Buffer('Hello World!'));`

should be updated to:

`ch.sendToQueue(q, Buffer.from('Hello World!'));`

**Comment by michaelklishin** [comment]
@Robinnnnn feel free to submit a pull request to this repo against the `live` branch as well as [rabbitmq-tutorials](https://github.com/rabbitmq/rabbitmq-tutorials/).

**Comment by michaelklishin** [comment]
Thank you, @Robinnnnn, for contributing.
