### ISSUE TITLE
newer erlang packages to packagecloud (or other repo source)?

### ISSUE THREAD

**Issue by wyardley** [rabbitmq/rabbitmq-website#235]
https://www.rabbitmq.com/install-rpm.html helpfully references packagecloud, and it seems that the rabbitmq package for erlang is there too, in a different repo:
https://packagecloud.io/rabbitmq/erlang
However, it doesn't seem to be up to date with all the packages available at
https://www.rabbitmq.com/releases/erlang/, and only has the el6 one (to be fair, the el7 package will work with the version of erlang distributed with el7, however, the autocluster plugin won't, and it's still below the version that rabbitmq recommends using for certain features).

Is this the right place to mention this, and would it be possible to update the newer packages, including the el7 ones, to there?

**Comment by michaelklishin** [comment]
Perhaps when 18.3.4 and 19.0 ones are published as final releases.

This repository has little to do with packaging.

**Comment by michaelklishin** [comment]
[Zero dependency Erlang RPM](https://github.com/rabbitmq/erlang-rpm) has a separate repo and releases.
