### ISSUE TITLE
Broken link for management API documentation

### ISSUE THREAD

**Issue by zbentley** [rabbitmq/rabbitmq-website#245]
The management API's documentation is linked in `https://www.rabbitmq.com/management.html`. 

The documentation is served from githack.com (the management repo), and contains a broken link, entitled `the separate stats documentation`. 

I'm not sure if this is an issue with githack and relative links, or if it's an issue with the link on the page in the management API itself (in which case this issue should be closed/moved to the `rabbitmq-management` repo).

**Comment by michaelklishin** [comment]
It's not broken if you go to `/api` on any node that runs the management plugin but yes, this should be addressed somehow.

**Comment by michaelklishin** [comment]
I think this was addressed since 2016.
