### ISSUE TITLE
Cluster docs fail to mention Erlang distribution port

### ISSUE THREAD

**Issue by davidstelter** [rabbitmq/rabbitmq-website#297]
The clustering docs have a fairly significant omission. The section on "Firewalled nodes" mentions the RabbitMQ clustering port and the epmd port, but make no mention of the Erlang distribution ports, which are required.

There should be mention of these ports, their default behavior of not being a set port but rather an arbitrary range determined at runtime, and controlling these ports in the rabbitmq.config file via the kernel settings inet_dist_listen_min and inet_dist_listen_max.

There's a good discussion of a simple and workable approach to this here: http://thesoftjaguar.com/posts/2014/06/18/rabbitmq-cluster/

Gist is, set the range to a single port and then you can open that one port in your firewall and/or security group rules.

**Comment by michaelklishin** [comment]
Port Access on http://www.rabbitmq.com/networking.html and a few installation guides do mention the default distribution port, which is [a range of 1](https://github.com/rabbitmq/rabbitmq-server/blob/1b0096a925ba56af16d4776713a5c8e9593c587a/scripts/rabbitmq-env#L175) by default in reasonably recent versions.

**Comment by michaelklishin** [comment]
An easy way to verify what the default value is on a vanilla node:

```
rabbitmqctl environment | grep inet_dist_listen
      {inet_dist_listen_max,25672},
      {inet_dist_listen_min,25672}]},
```

We will mention those `kernel` settings but the default already is what you are asking for.

**Comment by michaelklishin** [comment]
I reworked several sections related to ports in the Networking, Clustering and Configuration guides.
Thank you for reporting this.

**Comment by davidstelter** [comment]
Well, glad it led to clarifications in the docs, but I think I'd confused myself - I couldn't get the join_cluster command to work until I specified the port in the config, failed with a weird "node is up/node is down" message every time, but now I've torn down and recreated the cluster successfully on the default port without changing any firewall/security group mappings, which have both the default of 25672 as mentioned in the clustering docs as well as the weirdo port I got from that blog entry... Guess I must have been doing something else wrong, but I have no idea what.
