### ISSUE TITLE
Changelog is missing 3.5.8

### ISSUE THREAD

**Issue by professor** [rabbitmq/rabbitmq-website#307]
I noticed that the change log does not list 3.5.8, which appears to be the preferred 3.5.x release due to a security fix. 

http://www.rabbitmq.com/changelog.html

https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_5_8

**Comment by michaelklishin** [comment]
It [is not missing](https://github.com/rabbitmq/rabbitmq-website/blob/live/site/changelog.xml#L45).

**Comment by michaelklishin** [comment]
3.5.8 is the second release from the top on http://www.rabbitmq.com/changelog.html (the list is in reverse chronological order).

**Comment by professor** [comment]
We were upgrading a rabbit 3.5.2 installation to 3.5.7 and did not see 3.5.8 since it is not listed near the 3.5.x releases. We expect releases to be sorted by release number then date. 

Sorting by date, not release allowed us to miss an important security fix.

**Comment by michaelklishin** [comment]
@professor I'm sorry but we can't assume it works that way for everybody. We announce releases on rabbitmq-users and Twitter (in fact, multiple times per release on Twitter). I suggest that you sign up for one of those.

We will not be changing the order based on one data point.

**Comment by michaelklishin** [comment]
GitHub releases are also sorted by date (by tag date, to be precise), not version order.
