### ISSUE TITLE
tutorial-five(topics) teaser_answer_2 is wrong

### ISSUE THREAD

**Issue by javaforfun** [rabbitmq/rabbitmq-website#317]
[https://www.rabbitmq.com/tutorials/tutorial-five-python.html#teaser_answer_2](https://www.rabbitmq.com/tutorials/tutorial-five-python.html#teaser_answer_2)
>Will "#.\*" catch a message with a string ".." as a key? Will it catch a message with a single word key?
>No. (but I don't know why!)
>       ./receive_logs_topic.py "#.\*"
>       ./emit_log_topic.py ".."

it should be Yes.  i've tested on management ui

**Comment by michaelklishin** [comment]
I think the entire thing has to go because that question has little practical value.
