### ISSUE TITLE
Instruction for building server package is incorrect

### ISSUE THREAD

**Issue by mydiemho** [rabbitmq/rabbitmq-website#326]
The [instruction](http://www.rabbitmq.com/build-server.html#building-debian-package) for building Debian packages said to run this 
```
make package-deb VERSION=x.y.z.build UNOFFICIAL_RELEASE=true
```

However, I get an error when I'm trying to build version 3.6.5 on a Xenial machine:

```
~/rabbitmq-server-3.6.5$ make package-deb VERSION=3.6.5 UNOFFICIAL_RELEASE=true
make: *** No rule to make target 'package-deb'.  Stop.
```

**Comment by michaelklishin** [comment]
All packaging bits were [moved to rabbitmq-server-release](https://github.com/rabbitmq/rabbitmq-server-release).

**Comment by mydiemho** [comment]
With the new repo, can we still build older versions?  

I'm still getting error:

```
cp -a /home/rabbitmq-server-release/PACKAGES/rabbitmq-server-3.7.0.milestone8.tar.xz rabbitmq-server_3.6.5.orig.tar.xz
xzcat rabbitmq-server_3.6.5.orig.tar.xz | tar -xf -
rsync -a \
	--exclude '.sw?' --exclude '.*.sw?' \
	--exclude '.git*' \
	--delete --delete-excluded \
	debian/ rabbitmq-server-3.6.5/debian/
rsync: mkdir "/home/rabbitmq-server-release/packaging/debs/Debian/rabbitmq-server-3.6.5/debian" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.1]
Makefile:35: recipe for target 'package' failed
make[2]: *** [package] Error 11
make[2]: Leaving directory '/home/rabbitmq-server-release/packaging/debs/Debian'
Makefile:72: recipe for target 'package-deb' failed
make[1]: *** [package-deb] Error 2
make[1]: Leaving directory '/home/rabbitmq-server-release/packaging'
Makefile:214: recipe for target 'package-deb' failed
make: *** [package-deb] Error 2
```

**Comment by michaelklishin** [comment]
Why do you need to build a Debian package of 3.6.5?

**Comment by mydiemho** [comment]
we want to build and keep packages for our own deployment for better security tracking.

**Comment by michaelklishin** [comment]
Our build system does not assume that past packages
may need rebuilding.

You are trying to build from master, by the way.

**Comment by mydiemho** [comment]
Forgive my lack of knowledge, but what branch should I build on then?

Here's the script I use:

```
#!/bin/bash

set -e

VERSION=$1

if [[ -z $VERSION ]]; then
    echo ERROR: "must specify the build version (i.e. 3.6.5)"
    exit 1
fi

echo "Ensuring packages exist..."
sudo apt-get update && apt install -y debhelper erlang-dev erlang-src python-simplejson \
            xmlto xsltproc erlang-nox zip rsync elixir

rm -rf rabbitmq-server-$VERSION
git clone https://github.com/rabbitmq/rabbitmq-server-release.git

cd rabbitmq-server-release
make package-deb VERSION=$VERSION UNOFFICIAL_RELEASE=true
```

**Comment by michaelklishin** [comment]
You need to check out the umbrella, switch to the right tag with `make up BRANCH={something that git can check out}`, and then use the build procedure that was used at that point in time.

You cannot build an older version from master or stable (which is what I was referring to by "rebuilding" above).

**Comment by michaelklishin** [comment]
Not sure how to proceed with this but in general, with [development alpha builds](https://bintray.com/rabbitmq/all-dev/) now being produced by our CI/CD pipeline, building from source is not necessary nearly as often.
