### ISSUE TITLE
Might be couple of broken links in website

### ISSUE THREAD

**Issue by everydaysasaturday** [rabbitmq/rabbitmq-website#332]
FYI,

I encountered a couple of links in the webpages (at least in http://next.rabbitmq.com/configure.html#config-file) where the links are pointing to e.g. https://github.com/rabbitmq/rabbitmq-server/blob/stable/docs/advanced.config.example. The classic config file link is pointing to wrong url also.

but the correct link is found from https://github.com/rabbitmq/rabbitmq-server/blob/master/docs/advanced.config.example

changing the stable to master in the link gives you the correct address.

Can't remember where else this was but this advanced.config.example was not the only one.

**Comment by michaelklishin** [comment]
Once 3.7.0 they should be pointed at `stable` again, because then `stable` will be `3.7.x`. But corrected for now. Good to see people trying out new config formats and using `next.rabbitmq.com` in general.
