### ISSUE TITLE
Properly document DefaultBasicConsumer

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-website#34]
Currently the docs recommend `QueueingBasicConsumer`, which is no longer relevant in `3.5.0` due to concurrent dispatch used by channels. It also cannot be recovered by automatic recovery and is error prone.

It's a real shame we are in this situation with the .NET guide.

**Comment by natialmagor40** [comment]
hi
 i 'm using QueueingBasicConsumer for dequeue  , i understand that is not support autorecovery is ther workaround for it?

**Comment by michaelklishin** [comment]
@natialmagor40 please use rabbitmq-users for questions. The workaround is to perform your own recovery using recovery listeners. With the way queueing consumers are typically used (in a while loop of some kind), it won't be easy.

**Comment by natialmagor40** [comment]
can u link a sample?

**Comment by michaelklishin** [comment]
I don't have one and my suggestion would be "if you want recovery, don't use queueing consumers".

**Comment by natialmagor40** [comment]
what consumer should i use?

**Comment by michaelklishin** [comment]
I'd simply subclass `DefaultConsumer` and override the methods you want. Or implement the `Consumer` interface however you please ;)

**Comment by natialmagor40** [comment]
i'm lloking for blocking consumer , what functions should ovveride

**Comment by michaelklishin** [comment]
I've removed all comments not related to this issue.

**Comment by natialmagor40** [comment]
it is sadly that there no workaround for consumer recovery

**Comment by michaelklishin** [comment]
Was fixed in 1e340d5cba1b5e39812be36fe49c1cdc6b2222f2.
