### ISSUE TITLE
list-of-ports.xml.inc does not indicate the sources for the ports

### ISSUE THREAD

**Issue by FlorinAndrei** [rabbitmq/rabbitmq-website#343]
The document shows a list of ports, but does not indicate the source for each type of port. Possible sources are:
- RMQ clients
- management tools
- other nodes in the RMQ cluster
- CLI

It would be great if the list indicated, for each port, that it should be opened from:
- RMQ clients
- all other nodes in the cluster
- management tools
- any place that runs the CLI
- etc

**Comment by michaelklishin** [comment]
That snippet is shared between multiple guides. We don't want to turn all of them into the Networking one. So it belongs to the Networking guide.

**Comment by FlorinAndrei** [comment]
I understand. But keep this in mind:

- simply indicating the port number is worthless. When you open a port, you always open it for some source IPs. The document as it is now seems to say "open those ports to the world", which is a lot of people will do, and it's of course bad (remember the wide-open Mongo servers?)
- the document does not have to become a treatise on network security. It's enough to add, to each line: "open from client IPs", or "open from management IPs", or "open from RMQ cluster IPs", etc

Maybe it's my network security background that really bothers me when I look at those port numbers and I don't see any source IP specified anywhere. To a lot of folks that would mean a blank check to open from `0.0.0.0/0`. Let's not make it easier for people to make bad decisions.

**Comment by michaelklishin** [comment]
You are making bold claims, sir. They may be worthless to you but the list of ports has been around for years and this is the first time we have this feature request.

**Comment by michaelklishin** [comment]
Or perhaps it's because we do mention what each port does, at least we do mention protocols and plugins that use them and specifically call out the inter-node traffic port in the Port Access section on http://www.rabbitmq.com/networking.html. So I consider this a point of improvement but not an issue as a reasonable amount of information is already there.

**Comment by michaelklishin** [comment]
I added more details, 2 more ports (for Web STOMP and Web MQTT plugins) and links to epmd, MQTT, STOMP, etc. The list now assumes less familiarity with messaging protocols, what they are used for in RabbitMQ, and so on. Thank you for the feedback.

**Comment by FlorinAndrei** [comment]
It's a lot easier to understand now if you're not familiar with RMQ. Thank you.
