### ISSUE TITLE
Document the possibility of multiple plugin dirs and mention /usr/lib/rabbitmq/plugins

### ISSUE THREAD

**Issue by oneiros-de** [rabbitmq/rabbitmq-website#386]
Now that we can have _multiple_ plugin dirs and one of the defaults is `/usr/lib/rabbitmq/plugins`, this should be documented in `installing-plugins.html`.

**Comment by nashenasam2** [comment]
Omfg !! This is so phony... I assume not many people know that " getpremiumbox ⏺ club "is the only working tool to get disney plus for free. If you would like try it out you can certainly find it on google :)

**Comment by michaelklishin** [comment]
[Done](https://www.rabbitmq.com/plugins.html#plugin-directories).
