### ISSUE TITLE
Clarify "auto-delete" for queues

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-website#393]
Right now this is the only place that clearly states a queue must have had at least one consumer before it is eligible for auto-deletion:

https://www.rabbitmq.com/amqp-0-9-1-reference.html#queue.declare.auto-delete

This page could be improved:

http://www.rabbitmq.com/tutorials/amqp-concepts.html

> Auto-delete (queue is deleted when last consumer unsubscribes)

Docs reviewed due to [this `rabbitmq-users` discussion](https://groups.google.com/forum/#!topic/rabbitmq-users/-a5HvbX9niE)

**Comment by michaelklishin** [comment]
We introduced a [separate guide for queue properties](http://rabbitmq.com/queues.html) and other bits that do not clearly fit anywhere else.
