### ISSUE TITLE
Update .NET client API reference for 4.x

### ISSUE THREAD

**Issue by ebelew** [rabbitmq/rabbitmq-website#396]
The rabbitmq .net client has bene updated to 4.1.3 (as of 2017-06-16), but the documentation link still goes to 3.6.10.

Target Page: https://www.rabbitmq.com/dotnet.html

**Comment by michaelklishin** [comment]
[Documentation guide](https://www.rabbitmq.com/dotnet-api-guide.html) is up-to-date. API reference isn't but there weren't any major API changes.

@kjnilsson did we settle on any JavaDoc-like tool to use in the future?

**Comment by ebelew** [comment]
@michaelklishin There are actually some significant changes. 

Example: `BasicPublish` only has one signature in 4.x, but there are 3 in 3.6.10.   
https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/api/IModel.cs#L221 
  vs  
https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/stable/projects/client/RabbitMQ.Client/src/client/api/IModel.cs#L255 to line 270

**Comment by kjnilsson** [comment]
These (and more) are implemented as extension methods.
