### ISSUE TITLE
Update documentation for strict umask

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-website#399]
Update documentation for the issue https://github.com/rabbitmq/rabbitmq-server/issues/1129

See this comment for details: https://github.com/rabbitmq/rabbitmq-server/issues/1129#issuecomment-311602127

**Comment by michaelklishin** [comment]
I started in acd5daf2fc443aa3c341bfd28c7db71c8022df31, have a couple more updates in mind.

**Comment by michaelklishin** [comment]
I ended up making this a generic paragraph, in part because specific umask settings or permissions won't make much sense to Windows users. If someone feels it's worth providing OS-specific examples, feel free to add them.
