### ISSUE TITLE
Tutorial 1, Ruby: Snippets on web inconsistent with combined receive.rb file

### ISSUE THREAD

**Issue by merichar** [rabbitmq/rabbitmq-website#403]
The receive.rb snippets on the tutorial web page [https://www.rabbitmq.com/tutorials/tutorial-one-ruby.html](https://www.rabbitmq.com/tutorials/tutorial-one-ruby.html) are inconsistent with the summary file [https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/ruby/receive.rb](https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/ruby/receive.rb) 

Most differences are inconsequential, but the web snippet source, once combined, behaves incorrectly. It only dequeues one message per execution. The file was obviously updated to solve this problem, (though strangely also no longer mentions the queue name on the "waiting for messages" puts) and those changes were never reflected in the page snippets.

Relevant web snippet:
```
puts " [*] Waiting for messages in #{q.name}. To exit press CTRL+C"
q.subscribe(:block => true) do |delivery_info, properties, body|
  puts " [x] Received #{body}"

  # cancel the consumer to exit
  delivery_info.consumer.cancel
end
```

Relevant file snippet:
```
begin
  puts " [*] Waiting for messages. To exit press CTRL+C"
  q.subscribe(:block => true) do |delivery_info, properties, body|
    puts " [x] Received #{body}"
  end
rescue Interrupt => _
  conn.close
  exit(0)
end
```

**Comment by michaelklishin** [comment]
@merichar good catch. Should be in sync now. Thank you for reporting!
