### ISSUE TITLE
Missing value for `multiple` instructions on http://www.rabbitmq.com/confirms.html

### ISSUE THREAD

**Issue by zbentley** [rabbitmq/rabbitmq-website#404]
When instructing users to set the `multiple` bit to enable multi-conforms, the confirms webpage appears to instruct users to set an empty value in the beginning of the second paragraph in the multiple-confirms section.

The offending HTML is here:
`When the <span class="code ">multiple</span> field is set to <span class="code "></span>, RabbitMQ will acknowledge`...

There is no value between the second set of `span` tags.

This is present in Safari, Chrome, and Firefox on OSX, and does not appear to be browser-related; just a typo.

**Comment by michaelklishin** [comment]
Yup, thanks for reporting.

**Comment by michaelklishin** [comment]
A fix is live.

**Comment by zbentley** [comment]
Awesome, thanks!
