### ISSUE TITLE
Misleading documentation for HA at https://www.rabbitmq.com/ha.html

### ISSUE THREAD

**Issue by tomjonandy** [rabbitmq/rabbitmq-website#423]
In the "How Mirroring is Configured" section it is implied that the `x-arguments` method still works, whereas this was apparently discontinued as in http://www.rabbitmq.com/blog/2012/11/19/breaking-things-with-rabbitmq-3-0/.

**Comment by michaelklishin** [comment]
@tomjonandy I deployed some edits. Please let me know if sufficient in your opinion.

**Comment by tomjonandy** [comment]
@michaelklishin This is much better, thank you! - just one small thing, it still says "we should take a look at how it had been done historically" in the first sentence which now doesn't make sense.

**Comment by michaelklishin** [comment]
@tomjonandy corrected, thanks again!
