### ISSUE TITLE
Inter-node clustering with TLS is not documented well for Windows

### ISSUE THREAD

**Issue by bjalonmontanes** [rabbitmq/rabbitmq-website#426]
A rabbitmq user claimed that was able to set secure a cluster (Inter-node) and CLI Tool Communication with TLS (SSL) in Windows and they would like to have this documented for Windows too.

I was able to do it too but there are some small differences.

 - The command to get the path to the Erlang ssl library didn't work in windows.

```
echo `erl -eval 'io:format("~p", [code:lib_dir(ssl, ebin)]),halt().' -noshell`
"/path/to/erl/lib/ssl-5.3.5/ebin"
```

I had to manually find it.

- If the path has spaces, you need to put it between quotation marks when setting _ ERL_SSL_PATH_ . E.g

```
set ERL_SSL_PATH="C:\Program Files\erl8.2\lib\ssl-8.1\ebin"
```

- Quotation marks are also needed when providing the _server_certfile_ parameter in _RABBITMQ_CTL_ERL_ARGS_, if the path has spaces. E.g
```
set RABBITMQ_CTL_ERL_ARGS=-pa %ERL_SSL_PATH% -proto_dist inet_tls -ssl_dist_opt server_certfile "C:\Program Files\RabbitMQ Server\rabbitmq_server-3.6.9\rabbit.pem" -ssl_dist_opt server_secure_renegotiate true client_secure_renegotiate true
```
- Commando for concatenating the server certificate and key into one file is _type_, E.g. 
```
Type cert.pem key.pem> rabbit.pem
```

The user used self-signed certificate as explained in https://www.rabbitmq.com/ssl.html and imported the certificate in the Windows Certification Manager. But I tried without doing it and it worked.

Apart from this, instruction in https://www.rabbitmq.com/clustering-ssl.html for Linux, worked for Windows too.

Hope this helps to complete the documentation. 
 
P.S The only thing that worked for that user and not for me was only thing that didn’t work was using `openssl s_client -connect hostname:25672` to test he connection. I get a ssl handshake failure whereas user sees a good output.

**Comment by wtheronjones** [comment]
I second this request.  I'm having quite a lot of pain getting SSL setup on windows,

I would welcome a working example.

**Comment by lukebakken** [comment]
Is this the topic to which you are referring? [link](https://groups.google.com/d/topic/rabbitmq-users/DJC6keLJdi0/discussion)

**Comment by wtheronjones** [comment]
Thanks, but I am not yet to the point where I am dealing with ssl + clustering on Windows.      

I do notice that the documentation on this page says the Windows specific docs are “TBD”, which means this will be fun when the time comes.

I’m merely trying to connect to an ssl enabled rabbit instance w/ a client side certificate and it doesn’t work even though I thought I followed the steps. 

I also am wondering about some of the considerations re: certificates and Windows in an enterprise network scenario(not world wide web).

Thanks,
-Wes
