### ISSUE TITLE
v3.5.8 distribution files missing

### ISSUE THREAD

**Issue by sclo** [rabbitmq/rabbitmq-website#429]
Hello,

Could you add files for the release v.3.5.8 like https://www.rabbitmq.com/releases/rabbitmq-server/v3.5.7/ at https://www.rabbitmq.com/releases/rabbitmq-server/v3.5.8/ ?

Thanks !

**Comment by dumbbell** [comment]
Hi!

Sure! Let me take care of that. I'll get back to you when it's ready.

**Comment by dumbbell** [comment]
The files are now available.

Thank you for reporting the problem!

**Comment by michaelklishin** [comment]
@sclo if you are relying on `rabbitmq.com/releases/*` for anything, consider switching to GitHub or Bintray. That directory may or may not be around for long. Bintray contains an [archive of releases](https://bintray.com/rabbitmq/archive) that predate the switch to GitHub (happened around 3.5.0 IIRC).
