### ISSUE TITLE
Invalid argument name on tutorial step three - python

### ISSUE THREAD

**Issue by mortezaipo** [rabbitmq/rabbitmq-website#433]
There is an incorrect method argument in `tutorial step three - python`:
```python
#!/usr/bin/env python
import pika
import sys

connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
channel = connection.channel()

channel.exchange_declare(exchange='logs',
                         type='fanout')
```
In `exchange_declare` there is no `type` method when connection is `BlockingConnection`.  This argument should be `exhange_type` instead of `type`:
```python
channel.exchange_declare(exchange='logs',
                         exchange_type='fanout')
```

**Comment by lukebakken** [comment]
@mortezaipo feel free to open a PR against the `live` branch of this repository. Thanks for finding that.

**Comment by michaelklishin** [comment]
@mortezaipo what Pika version do you use?

If Pika uses different argument names depending on connection type (why would it if it's a channel method? 😕 ), we should also leave a comment about that.

**Comment by mortezaipo** [comment]
@michaelklishin I'm using the stable version: "0.9.5"

Today I've checked the other version, version "0.10.0" and later support `kwargs` in `exchange_declare` method and it will check `type` value:
http://pika.readthedocs.io/en/0.10.0/modules/adapters/blocking.html#pika.adapters.blocking_connection.BlockingChannel.exchange_declare

This is the code that checks `kwargs`:
```python
...
arguments=arguments,
type=kwargs["type"] if kwargs else None)
```

But in my version which I'm using, `kwargs` doesn't exist in this method:
http://pika.readthedocs.io/en/stable/modules/adapters/blocking.html#pika.adapters.blocking_connection.BlockingChannel.exchange_declare

Actually I wish to know that website is based on _stable_ version or _beta_ version of Pika?

**Comment by michaelklishin** [comment]
@mortezaipo Pika is at 0.11.0 and 0.10.0 existed well over 1 year ago. The website targets the most recent GA release, which is 0.11.0 (we are not aware of incompatibilities with 0.10.0 as far as the tutorials go).

**Comment by michaelklishin** [comment]
According to PyPI, even Pika 0.9.9 was [released in early 2013](https://pika.readthedocs.io/en/0.9.9/). That's not stable. That's obsolete.

**Comment by michaelklishin** [comment]
I'm going to make it clearer what version of Pika is targeted (the tutorials only say "using Pika 0.10.0" in one place at the top).

I'm curious what page hinted you off on the 0.9.5 being the "stable" version? Maybe some package metadata that simply wasn't updated?

**Comment by michaelklishin** [comment]
[setup.py in master](https://github.com/pika/pika/blob/master/setup.py#L33) seems to have a reasonable Development Status value.

**Comment by michaelklishin** [comment]
All tutorials now mention that [Pika 0.11.0 is required](http://www.rabbitmq.com/tutorials/tutorial-two-python.html) (technically it's 0.10.0 but 0.11.0 includes a year worth of community contributions, so let's recommend that).

**Comment by mortezaipo** [comment]
@michaelklishin thank you so much for your updates.
I've checked all codes with old package and it was my mistake.
Respectfully accept my apologize.

**Comment by michaelklishin** [comment]
@mortezaipo no worries. Thank you for bringing this up to our attention!
