### ISSUE TITLE
Website example seems incorrect

### ISSUE THREAD

**Issue by silverdaz** [rabbitmq/rabbitmq-website#441]
I was looking for the [recipe to create password hashes](https://www.rabbitmq.com/passwords.html).

I ran the example on the website, but I can't reproduce the same results. Namely:

```
echo -n 908DC60A746573743132 | openssl dgst -sha256
8a2740eb25e09965fba5fb9259e00f3d37119ae6b2fe07e9a3d2e93ccdd88428
```

which doesn't match the result on the website:

```
A5B9 24B3 096B 8897 D65A 3B5F 80FA 5DB62 A94 B831 22CD F4F8 FEAD 10D5 15D8 F391
```

So, that confuses me, and I can't produce correct password hashes.
Maybe it was a simple miss to update https://github.com/rabbitmq/rabbitmq-website/blob/master/site/passwords.xml#L219-L220 but when I try to  use the password hash generated that way, I get "Invalid credentials".

Can you point me to the correct recipe, please?

**Comment by lukebakken** [comment]
Hello,

When you run that `echo` command, you are actually sending different byte values to `openssl` - the bytes correspond to the ASCII representation of the digits:

```
$ echo -n 908DC60A746573743132 | xxd
00000000: 3930 3844 4336 3041 3734 3635 3733 3734  908DC60A74657374
00000010: 3331 3332                                3132
```

What you want to do is run this command:

```
$ echo -n '908DC60A746573743132' | xxd -r -p | openssl dgst -sha256
(stdin)= a5b924b3096b8897d65a3b5f80fa5db62a94b83122cdf4f8fead10d515d8f391
```
