### ISSUE TITLE
403 Forbidden link for url http://www.rabbitmq.com/networking.html

### ISSUE THREAD

**Issue by folt** [rabbitmq/rabbitmq-website#442]
Hi, while studying the documentation I came across a link that does not work. 
page: http://www.rabbitmq.com/networking.html
text: "How the limit is configured"
link: http://docs.basho.com/riak/latest/ops/tuning/linux/
html: `<a href="http://docs.basho.com/riak/latest/ops/tuning/linux/">How the limit is configured</a>`

**Comment by michaelklishin** [comment]
@folt Basho has shut down their site recently. There's a ton of semi-complete posts on the Web about that but few things come close to the Riak guide :( I will link to [this one](https://ro-che.info/articles/2017-03-26-increase-open-files-limit) for now, it seems to touch all the relevant points.

**Comment by lukebakken** [comment]
We could link to the source directly here - https://github.com/basho/basho_docs/blob/master/content/riak/kv/2.2.3/using/performance/open-files-limit.md

It's in markdown so at least it renders OK.

**Comment by michaelklishin** [comment]
@lukebakken good idea. Done. I've noticed that the docs are CC 4.0 licensed so perhaps at some point we should incorporate the open file handle part into our guide.
