### ISSUE TITLE
.NET client tutorials should use named arguments everywhere

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-website#47]
As one can see in [tutorial 1](http://www.rabbitmq.com/tutorials/tutorial-one-dotnet.html), our tutorials use [named arguments](https://msdn.microsoft.com/en-us/library/dd264739.aspx) in some places but not everywhere. We should do that across the board as it makes the code a lot clearer to beginners.

**Comment by michaelklishin** [comment]
Why is this closed? We haven't merged #63 yet.

**Comment by priviterag** [comment]
Oops. Yep, you merged the tutorials not the website
