### ISSUE TITLE
Clients page had links removed

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-website#474]
Commit a05fbf1b202d827fa7fc4a2d75c3768068c25372 removed links from `clients.html`, but it's not apparent why.

"Remove links so that visitors landing here by mistake are not confused"

@gerhard - could you shed some light on this?

@dcarwin-pivotal

**Comment by dcarwin-pivotal** [comment]
as a visitor, I was confused by what appeared to me very clearly should be links, were not in fact links.
![image](https://user-images.githubusercontent.com/5297492/34895425-9325a986-f79a-11e7-8396-39065a7d1856.png)

**Comment by gerhard** [comment]
Removing those links does seem wrong, I wish I had captured more in the commit. Fixing it now, it might jog my memory.
