### ISSUE TITLE
Pages with table tags are still too wide on smaller screens (e.g. iPhone 6)

### ISSUE THREAD

**Issue by chenders** [rabbitmq/rabbitmq-website#488]
The [Highly Available (Mirrored) Queues page](https://www.rabbitmq.com/ha.html) looks like this at an iphone 6 width:

![www rabbitmq com_ha html iphone 6](https://user-images.githubusercontent.com/962076/35437454-4c3b56bc-0247-11e8-8895-d522dc49c12c.png)

The [meta-content tags in the page](https://github.com/rabbitmq/rabbitmq-website/blob/392ac1bcc5314fb462c15c2e1293638642309c27/wordpress-theme/header.php#L10) prevent the user from being able to scale it to fit, so the only way to read it is by scrolling horizontally back and forth. 

It appears that the cause of this is that the `<table>`s are not styled responsively. For example, the [JMS Client page](https://www.rabbitmq.com/jms-client.html) has the same issue.

**Comment by michaelklishin** [comment]
Thank you for providing the details.

**Comment by michaelklishin** [comment]
We have adjusted the layout to be more readable on smaller screens. While tables specifically do not look great, they are fairly readable (no content is cut). Below are iPhone SE and iPhone 8 emulators from desktop Safari Responsive Design mode:

<img width="689" alt="Screenshot 2020-09-11 at 15 00 39" src="https://user-images.githubusercontent.com/1090/92923267-d6146800-f43f-11ea-9f1e-ff305eb1e847.png">

<img width="688" alt="Screenshot 2020-09-11 at 15 00 55" src="https://user-images.githubusercontent.com/1090/92923299-e88ea180-f43f-11ea-85bb-4bc843ccbeef.png">

I don't have any more ideas about how tables can be made better for small screens in portrait orientation. Let us know if there are examples of doc sites that do this well.
