### ISSUE TITLE
javascript tutorial mentions rubygems

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-website#50]
See the teasers section here: https://github.com/rabbitmq/rabbitmq-website/blob/master/site/tutorials/tutorial-five-javascript.md

**Comment by priviterag** [comment]
fixed in https://github.com/rabbitmq/rabbitmq-website/pull/51

anyway, this feature does not work in any language tutorial. Not sure was working before or if it never worked

**Comment by michaelklishin** [comment]
Live.
