### ISSUE TITLE
Use Feature Of GoLang

### ISSUE THREAD

**Issue by poojabaghelsendinblue** [rabbitmq/rabbitmq-website#515]
Here the done channel is only used to synchronize the execution but not for sending data. There is a kind of pattern for such cases:
func main() {
     // Data is irrelevant
     done := make(chan struct{})

     go func() {
          println("goroutine message")

          // Just send a signal "I'm done"
          close(done)
     }()

     println("main function message")
     <-done
} ,
In GO AMQP library, We should close the Channel in reciever.go file

**Comment by lukebakken** [comment]
If you have suggestions for the content of the website, please open a pull request with the changes, reference this issue, and re-open this issue. Thank you.

**Comment by poojabaghelsendinblue** [comment]
ok

**Comment by poojabaghelsendinblue** [comment]
I tried to Create a PR but I was not able to do that

**Comment by michaelklishin** [comment]
@poojabaghelsendinblue our repos are public and everyone should be able to create a PR for a public repo (there is simply no way to opt out on GitHub).

You can post a patch (diff) snippet in a comment. Also, GitHub has [pretty detailed docs](https://help.github.com/articles/creating-a-pull-request/) on how to create a PR. Are you

**Comment by poojabaghelsendinblue** [comment]
I have to create a PR using Forking the repo.
Thank you
