### ISSUE TITLE
Bad link (404) for the Erlang client download links.

### ISSUE THREAD

**Issue by wuodland** [rabbitmq/rabbitmq-website#518]
I was trying to download an erlang Client from [this](https://www.rabbitmq.com/erlang-client.html) page, namely the  [AMQP client library .ez archive](https://www.rabbitmq.com/releases/rabbitmq-erlang-client/v3.7.4/amqp_client-3.7.4.ez). But the files aren't available on the site. Even the  [RabbitMQ common library .ez bundle](https://www.rabbitmq.com/releases/rabbitmq-erlang-client/v3.7.4/rabbit_common-3.7.4.ez) and the [Source code](https://www.rabbitmq.com/releases/rabbitmq-erlang-client/v3.7.4/amqp_client-3.7.4-src.tar.xz) & their signatures also lead to 404's.

**Comment by michaelklishin** [comment]
The signatures do not lead to a 404.

The client is now distributed via hex.pm, which will be reflected in the docs.
