### ISSUE TITLE
Fix some minor issues in dotnet tutorial docs

### ISSUE THREAD

**Issue by jfunction** [rabbitmq/rabbitmq-website#534]
I had some (very) minor gripes with the dotnet tutorials and thought I'd give back to the community a bit while I'm learning. In general, they are really great, though I found some things like small inconsistencies in how strings are formatted, or minor typos which aren't critical to understanding the tutorial but can be a bit distracting. 

Should I just make github edits under https://github.com/rabbitmq/rabbitmq-website/edit/live/site/tutorials/tutorial-n-dotnet.md, or pull-edit-push, or fork-edit-PR? What's the process here? 

One thing that I noticed is that often the docs will reference a method like `basicQos` where the dotnet method is called as `channel.BasicQos(0, 1, false)` (capital *B* since C# loves pascal casing for some reason). Is that something to open an issue about or can I just go in and make edits?

Thanks

**Comment by jfunction** [comment]
Oh man - and in [tut-six-dotnet](https://www.rabbitmq.com/tutorials/tutorial-six-dotnet.html) the "Callback queue" example starts using `CorrelationId` before it explains what that is. For example, in [tut-six-python](https://www.rabbitmq.com/tutorials/tutorial-six-python.html) (my home language) the `correlation_id` is only set later on. So, I might make a few more edits than I thought... I'll put them in different commits though so it's clear what happened. 

I just don't want to do that work for nothing - should I submit a PR to the live branch?

**Comment by lukebakken** [comment]
A PR against the `live` branch would be great, thanks.

**Comment by michaelklishin** [comment]
Any process that results in a PR with the correct base (`live`) would do :)

**Comment by michaelklishin** [comment]
Addressed in #535.
