### ISSUE TITLE
Remove setTimeout from JS Tutorials

### ISSUE THREAD

**Issue by nerdkid93** [rabbitmq/rabbitmq-website#542]
In the era of `async`/`await`, using `setTimeout` to queue up asynchronous tasks is mostly unneeded. I have plans to make a PR to re-write the JS tutorials to properly close the `rabbitmq` connections and channels so the `setTimeout` would no longer be necessary.

**Comment by lukebakken** [comment]
Thanks, we'll keep an eye out for the PR. I don't think there is a need to keep this issue open. If discussion is needed we prefer to use the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list.

**Comment by michaelklishin** [comment]
We do appreciate PRs here and feedback on our tutorials on the mailing list. Thank you!
