### ISSUE TITLE
Please remove trackers & advertising

### ISSUE THREAD

**Issue by tino** [rabbitmq/rabbitmq-website#559]
![image](https://user-images.githubusercontent.com/99524/42865359-b5c3c34e-8a69-11e8-8b8a-f3c9203be020.png)

Doesn't look too good to me on an open source project page 😔.

Also the TrustArc/Truste popup is really annoying and slow. Is it necessary as this site provides nothing that's under the "Functionality NOT Allowed" right?

![image](https://user-images.githubusercontent.com/99524/42865461-fcdf9366-8a69-11e8-8085-5b05fe63fa74.png)

**Comment by michaelklishin** [comment]
There is NO advertising on this site, go dive into the source. Besides Google Analytics and Twitter, and perhaps YouTube embeds on the home page there are no trackers involved.

We are required to use TrustArc by our corporate sponsor. We are looking at alternatives (there is no ETA) or at least a separate instance that does not contact 300 services of which we only use 2 or 3.

**Comment by michaelklishin** [comment]
Those who absolutely don't want TrustArc or any trackers have the option of running a local instance of the site. See the README, it is straightforward. Once you have a local copy running, remove Google Analytics, TrustArc and Twitter from the layout.
