### ISSUE TITLE
Typo on rabbitmq.com/protocols.html

### ISSUE THREAD

**Issue by loadaverage** [rabbitmq/rabbitmq-website#561]
Found a small typo:

HTTP section:

Note that since JSON RPC is a synchronous protocol, some parts of AMQP that depend on **aysnchronous** delivery to the client are emulated by polling.

**Comment by lukebakken** [comment]
Please feel free to open a [pull request](https://github.com/rabbitmq/rabbitmq-website/pulls) against the `live` branch. Thanks!

**Comment by loadaverage** [comment]
[done](https://github.com/rabbitmq/rabbitmq-website/pull/562)
