### ISSUE TITLE
Page (/Tab) Title (Order)

### ISSUE THREAD

**Issue by AllenJB** [rabbitmq/rabbitmq-website#577]
When viewing the online documentation, every page title starts with "RabbitMQ - " (this can be further exacerbated if the document specific title also starts with RabbitMQ, such as "RabbitMQ Configuration", resulting in "RabbitMQ - RabbitMQ Configuration"). If you have a number of tabs open and/or a low width window, this can make it difficult to relocate specific documentation.

Suggestion: Reorder the document titles so that the site title, "RabbitMQ", appears at the end and the specific document title is first. This will make it easier to locate open tabs.

**Comment by lukebakken** [comment]
We would welcome a pull request for this. Please base it on the `live` branch.

**Comment by michaelklishin** [comment]
Done.
