### ISSUE TITLE
make preview on Linux looks for libxslt in the wrong place

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-website#586]
`/usr/local/opt` is not a commonly used location for some very popular Linux distributions. References #578.

**Comment by lukebakken** [comment]
`/usr/local/opt` is used on OS X, not Link - [source](https://github.com/rabbitmq/rabbitmq-website/blob/live/Makefile#L18). Note the check for `Darwin`.

Did you see something else in a Linux environment? FWIW, `/usr/include/libxslt` works as a check on my Arch Linux workstation:

```
$ ll /usr/include/libxslt/
total 204
drwxr-xr-x   2 root root  4096 Nov 11  2017 .
drwxr-xr-x 403 root root 40960 Sep 17 07:07 ..
-rw-r--r--   1 root root   930 Nov 10  2017 attributes.h
-rw-r--r--   1 root root  2704 Nov 10  2017 documents.h
-rw-r--r--   1 root root  6903 Nov 10  2017 extensions.h
...
...
```

**Comment by michaelklishin** [comment]
So it looks for `libxslt` headers, which on Debian is a separate package. Then it requires a `pipenv` installation which using apt on Ubuntu is currently surprisingly painful (there is a PPA but it doesn't have Bionic releases so without manual edits to its apt source list file `apt-get update` will fail).

It was a good idea to list the "manual" steps for Debian in the README. Thanks to `pipenv`'s relative unavailability on Debian `make preview` is not at all a shortcut there.

**Comment by lukebakken** [comment]
OK I'll see if I can make this easier for other distros.

**Comment by michaelklishin** [comment]
The biggest stumbling block is pipenv installation. I don't think it's a major issue we should spend more time on, the apt way of installing things is more or less a one liner.
