### ISSUE TITLE
403 forbidden when trying to download a community plugin

### ISSUE THREAD

**Issue by matteosister** [rabbitmq/rabbitmq-website#593]
I'm trying to download a [community plugin](https://dl.bintray.com/rabbitmq/community-plugins/3.7.x/rabbitmq_delayed_message_exchange/) and I get a **403 forbidden** error. 
I tried also with other plugins in the list but the result is the same. Am I doing something wrong?
Many thanks.

**Comment by tarampampam** [comment]
Me too

**Comment by michaelklishin** [comment]
Bintray rate limits our org from time to time and blocks downloads. We've contacted support.
