### ISSUE TITLE
Signing key is unavailable from rabbitmq.com

### ISSUE THREAD

**Issue by saxus** [rabbitmq/rabbitmq-website#621]
Currently Cloudflare says, the rabbitmq-release-signing-key.asc - which is mentioned in the documentation - is unavailable with the reason "Origin is unreachable". Other mirrors and the website are working, only the signing key is unavailable.

Url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
Screenshot from cloudflare: https://i.imgur.com/w1nGEM7.png

The key is unavailable at least 1.5 hours so I opened this ticket because that problem doesn't looks temporary for me.

**Comment by lukebakken** [comment]
Hello, we are aware of this issue and are working on a fix. Please see [this](https://twitter.com/RabbitMQ/status/1060159806756057089).

**Comment by rolandjohann** [comment]
thanks for quick answer!
