### ISSUE TITLE
Tutorial Port Number Error/Typo

### ISSUE THREAD

**Issue by hammeramr** [rabbitmq/rabbitmq-website#641]
At all of your tutorial pages in the "Prerequisites" info box you say: "This tutorial assumes RabbitMQ is installed and running on localhost on standard port (5672)."  

But the standard port is actually 15672 not 5672.

[Here](https://www.rabbitmq.com/tutorials/tutorial-one-python.html) is a link to one of the tutorials.

**Comment by lukebakken** [comment]
`5672` is indeed the AMQP TCP port. `15672` is the HTTP port on which the management interface web site is served. If you can find a tutorial where that is confusing, please comment here. Thanks.

**Comment by hammeramr** [comment]
oh, sorry then. Thanks.
