### ISSUE TITLE
Update documentation for tutorial 6 for .NET

### ISSUE THREAD

**Issue by kennethkryger** [rabbitmq/rabbitmq-website#653]
The documentation mentions a while loop twice when describing the client code, but the code was re-written to use events instead in this commit: https://github.com/rabbitmq/rabbitmq-website/commit/3e1dc4a6dcfc8ee28543fdc23520c8a1b1ab080e

**Comment by lukebakken** [comment]
We'd be happy to review a pull request with changes. Thanks!

**Comment by niwrA** [comment]
I think this issue should be closed as the example is already online ... 

Wouldn't it make more sense if this example was using the Direct-To pattern now though?

**Comment by michaelklishin** [comment]
@niwrA we'd consider a PR that switched to Direct Reply-to. Please update the [runnable version](https://github.com/rabbitmq/rabbitmq-tutorials) first, though.
