### ISSUE TITLE
Incorrect docs on the Configuration page regarding config file clustering

### ISSUE THREAD

**Issue by luos** [rabbitmq/rabbitmq-website#658]
Hi, 

The current documentation incorrectly says that cluster_nodes configuration option can be used in the new style config files. If I try to use them, I get "attempted to set unknown variable error", see below. 

The correct setting name is `cluster_formation.classic_config.nodes.*`.

I attempted to make a fix, let me know if  you want to open a PR from it, or is this some misunderstanding on my part. 

This page has the working config:
https://www.rabbitmq.com/cluster-formation.html

Fix: https://github.com/luos/rabbitmq-website/commit/a3900ec9581bbf8a912e8f01a6171b075a94ec49

Thanks

```
rmq1.377.host | 08:33:54.841 [error] You've tried to set cluster_nodes.disc.1, but there is no setting with that name.
rmq1.377.host | 08:33:54.841 [error]   Did you mean one of these?
rmq1.377.host | 08:33:54.862 [error]     listeners.ssl
rmq1.377.host | 08:33:54.862 [error]     listeners.tcp
rmq1.377.host | 08:33:54.862 [error]     listeners.ssl.$name
rmq1.377.host | 08:33:54.862 [error] You've tried to set cluster_nodes.disc.2, but there is no setting with that name.
rmq1.377.host | 08:33:54.862 [error]   Did you mean one of these?
rmq1.377.host | 08:33:54.882 [error]     listeners.ssl
rmq1.377.host | 08:33:54.882 [error]     listeners.tcp
rmq1.377.host | 08:33:54.882 [error]     listeners.ssl.$name
rmq1.377.host | 08:33:54.882 [error] Error generating configuration in phase transform_datatypes
rmq1.377.host | 08:33:54.882 [error] Conf file attempted to set unknown variable: cluster_nodes.disc.2
rmq1.377.host | 08:33:54.882 [error] Conf file attempted to set unknown variable: cluster_nodes.disc.1
```

**Comment by michaelklishin** [comment]
I pulled your change manually. Don't hesitate to submit a PR in the future. Thank you!
