### ISSUE TITLE
Requeue order

### ISSUE THREAD

**Issue by maggyero** [rabbitmq/rabbitmq-website#665]
According to the RabbitMQ documentation on [_Consumer Acknowledgements_](https://www.rabbitmq.com/confirms.html#consumer-nacks-requeue):

> When a message is requeued, it will be placed to its original position in its queue, if possible. If not (due to concurrent deliveries and acknowledgements from other consumers when multiple consumers share a queue), the message will be requeued to a position closer to queue head.

So with a single client consumer, if the server queue is initially

> tail [c b a] head

and the client consumer consumes the head message ("a"), the server queue becomes:

> tail [c b] head

Then if the client consumer nacks the processed message, the message gets requeued in the server queue at the head (its "original position" as per the documentation) and the server queue should become:

> tail [c b a] head

Finally the client consumer should consume again the same head message ("a").

But that is not what I observed using the Python library [Pika](https://github.com/pika/pika). What I observed is that nacked messages gets requeued at the tail of the server queue, not at the head (the "original position"). Is the RabbitMQ documentation correct or is the library Pika correct?

**Comment by lukebakken** [comment]
Please see my response to pika/pika#1153. And, please use the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) for questions!
