### ISSUE TITLE
Custom search on rabbitmq.com returns no results

### ISSUE THREAD

**Issue by richlanc** [rabbitmq/rabbitmq-website#67]
I've tried using a couple of obvious searches such as "queue" and "channel" and I'm not getting any results.
Tried in Chrome and Firefox, same result.

Mentioned this on the rabbitmq-users mail list and was told it was a known issue and to create a ticket here.

**Comment by videlalvaro** [comment]
Fixed in https://github.com/rabbitmq/rabbitmq-website/commit/ba1c428caf71da472f58b72bec3c4a69f90eca5e
