### ISSUE TITLE
cluster_formation.aws.aws_use_private_ip

### ISSUE THREAD

**Issue by leynebe** [rabbitmq/rabbitmq-website#679]
The documentation lists "cluster_formation.aws.aws_use_private_ip", but the example displays "cluster_formation.aws.use_private_ip". The example shows the correct parameter.
Link: https://www.rabbitmq.com/cluster-formation.html#peer-discovery-aws-other-settings

**Comment by michaelklishin** [comment]
Good catch, thank you.
