### ISSUE TITLE
Mention client [un]awareness of cluster topology

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-website#73]
See [this mailing list thread](https://groups.google.com/forum/#!topic/rabbitmq-users/zyqK2fl4Ocg).

**Comment by sdarwin** [comment]
The documentation says "When a list of addresses is provided, a random one will be picked during recovery".  However, that strategy would be problematic where a string of random bad luck would cause repeated connection attempts to the failed host.
In fact, the code logic appears to loop through all the hosts, and so the explanation might be
"When a list of addresses is provided, the list is shuffled and all addresses are tried, one after the next"   I believe that is what happens and it's better than random.

**Comment by michaelklishin** [comment]
@sdarwin feel free to submit a pull request with improvements (against the `live` branch) :)
