### ISSUE TITLE
How to send large amounts of producer data to consumers without waiting in RabbitMQ

### ISSUE THREAD

**Issue by StudyTae** [rabbitmq/rabbitmq-website#740]
I am using `Python3.7` to send and receive data.

The problem I have is that when  producer send a lot of data, `RabbitMQ` receive all the data from `RabbitMQ` and broadcast it.

sendmessage.py:
~~~py
async def send(tx):
    transport, protocol = await aioamqp.connect(host=MQ_HOST,
                                                port=MQ_PORT,
                                                login=MQ_USER,
                                                password=MQ_SEED)

    channel = await protocol.channel()

    await channel.exchange_declare(exchange_name='event.tx',
                                   type_name='fanout')


    await channel.basic_publish(json.dumps(tx.to_dict()),
                                exchange_name='event.tx',
                                routing_key='')

    await protocol.close()
    transport.close()

txs = []
loop = asyncio.get_event_loop()
for i in range(1000):
    tx = create_tx()
    asyncio.ensure_future(send(tx))


loop.run_forever()
~~~

receive.py:
~~~py
async def event_run(self):
        try:
            transport, protocol = await aioamqp.connect(host=MQ_HOST,
                                                        port=MQ_PORT,
                                                        login=MQ_USER,
                                                        password=MQ_SEED)
        except aioamqp.AmqpClosedConnection:
            return

        try:
            self._channel = await protocol.channel()

            await self._channel.exchange_declare(exchange_name=TX_EXCHANGE,
                                                 type_name='fanout')

            await self._channel.queue_declare(queue_name=EVENT_NAME(self.name),
                                              exclusive=True)

            await self._channel.queue_bind(exchange_name=TX_EXCHANGE,
                                           queue_name=EVENT_NAME(self.name),
                                           routing_key='')

            await self._channel.basic_consume(self.process_event,
                                              queue_name=EVENT_NAME(self.name),
                                              no_ack=True)
        except aioamqp.ChannelClosed:
            if not transport.is_closing():
                transport.close()
~~~

There's no problem with sending one to ten data like the code shown above and testing it, but when you receive a large amount of data like 1,000, it takes too long to get it back and start broadcasting again broadcasting.

Even if I receive a large amount of data, how do I get it to broadcast as soon as I receive it?

If the code can't solve it, can we fix it instead through plug-ins such as management plug-ins?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
There is a couple of obvious issues in this code. There is no need to open a new connection for every message published. That's not how messaging protocols are supposed to be used ([connections should be long lived](https://www.rabbitmq.com/connections.html)). There is no need to open a new channel or declare an declare an exchange for every message published either. 

[Use PerfTest](https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/) to establish a baseline for your setup (node, cluster and workload), then see how your actual workload compares. There is a broad range of areas that can affect throughput and latency. Profilers, [metrics](https://www.rabbitmq.com/monitoring.html) of infrastructure, RabbitMQ nodes and application activity should be used to narrow the bottleneck down. Guessing is a terribly expensive way of doing it.

Please move this to the mailing list.

**Comment by michaelklishin** [comment]
Also worth mentioning that opening and closing connection in a tight loop will lead to a condition known as [high connection churn](https://www.rabbitmq.com/networking.html#dealing-with-high-connection-churn), which has well understood downsides, tuning and mitigation requirements. But the best way to mitigate is to avoid it entirely for the reasons mentioned in the above comment and the docs.
