### ISSUE TITLE
protected emails in documentation

### ISSUE THREAD

**Issue by Monnick** [rabbitmq/rabbitmq-website#753]
When opening the website for reading the documentation, every text which contains the letter '@' is being replaced by [email protected]. Even the node names (for example: rabbit@rabbit2).
This results in a nearly unreadable document:
![RabbitMQ_Docu_Noscript](https://user-images.githubusercontent.com/24450458/57223987-369fc380-7008-11e9-9283-37f195dd4d23.png)

For reproducing this issue, open https://www.rabbitmq.com/clustering.html with incognito mode of the browser or disable java script.

**Comment by michaelklishin** [comment]
This is done by one of the plugins. Those values are not emails. Those so concerned with tracking that they disable JavaScript can run the site locally with any modifications they see fit, see README.

**Comment by michaelklishin** [comment]
I tried 3 browsers in Private/Incognitor mode with JavaScript enabled but all plugins besides a password manager disabled. Nothing is edited out, as expected:

<img width="998" alt="Screenshot 2019-05-06 at 21 59 44" src="https://user-images.githubusercontent.com/1090/57248273-a171ee80-704a-11e9-8657-6f043a8d134c.png">
<img width="859" alt="Screenshot 2019-05-06 at 22 00 26" src="https://user-images.githubusercontent.com/1090/57248278-a3d44880-704a-11e9-899f-59b3ae331a4b.png">
<img width="996" alt="Screenshot 2019-05-06 at 22 01 23" src="https://user-images.githubusercontent.com/1090/57248288-a898fc80-704a-11e9-9018-bb78e2ddf356.png">
