### ISSUE TITLE
Mirrors & availability

### ISSUE THREAD

**Issue by martinb3** [rabbitmq/rabbitmq-website#77]
Hi there!

I'm installing RabbitMQ on a somewhat regular basis through CI, and from time to time, it seems like rabbitmq.com is unavailable. While not very common, it seems to be at least a few times a year:

2015 March 4 - https://twitter.com/RabbitMQ/status/573051967846678528, https://github.com/travis-ci/travis-ci/issues/3330
2015 June 17 - http://permalink.gmane.org/gmane.comp.networking.rabbitmq.general/42670
2015 September 16 - (currently down)

Is there a better mirror to download packages from? Or anything I can do to help? Cheers!

**Comment by michaelklishin** [comment]
GitHub, Package Cloud, Bintray, as mentioned in [various installation guides](http://www.rabbitmq.com/download.html). Our signing key is also [available from Bintray](https://bintray.com/artifact/download/rabbitmq/Keys/rabbitmq-signing-key-public.asc).

Please use rabbitmq-users for questions in the future.

**Comment by michaelklishin** [comment]
Also, we plan on adapting our build system so that artifacts and the site are hosted on multiple machines behind rabbitmq.com but this will take some time and cooperation from other teams.

**Comment by martinb3** [comment]
Thanks @michaelklishin. I'll refer that back to the appropriate places to see if we can get the upstream cookbooks using a different mirror or more than one mirror. If there's anything I can do to help with your project for rabbitmq.com, or if I can put you in touch with folks @ Rackspace who might be able to help you mirror packages in some way, please let me know. Cheers!

**Comment by martinb3** [comment]
Looks like PackageCloud and BinTray are no longer listed on the [Downloads page](http://www.rabbitmq.com/download.html) and haven't had releases of rabbitmq-server packages since August, and are out of sync with rabbitmq.com. Sounds like maybe Github is the only mirror right now with the latest options.

**Comment by michaelklishin** [comment]
I am updating Bintray and Package Cloud today.

**Comment by michaelklishin** [comment]
Package Cloud is still [listed on the Debian repository page](http://www.rabbitmq.com/install-debian.html). For various (not really technical) reasons we are more likely to use Bintray in the long term but PC is currently available.

**Comment by martinb3** [comment]
I'm assuming you're only pushing them cuz I mentioned it? Until 10 minutes ago, the last update was from 6 months ago on PackageCloud:

```
rabbitmq-server-3.5.6-1.noarch.rpm el/6
pushed by rabbitmq 14 minutes ago

rabbitmq-server-3.4.4-1.suse.noarch.rpm el/6
The RabbitMQ server
```

I'm guessing it's also missing intermediate versions?

**Comment by michaelklishin** [comment]
@martinb3 last release on PC prior to 3.5.6 was in August (3.5.4), now removed.

We were not given a green light to go all in on Package Cloud, so we only keep the most recent releases of 3.5.x and 3.4.x there, in order to stay under the free plan quota.

Publishing to Bintray (and, hopefully, Package Cloud) will be integrated into the build system after 3.6.0 because we're [reworking it almost from scratch](https://github.com/rabbitmq/rabbitmq-server/compare/erlang.mk) at the moment.

**Comment by martinb3** [comment]
That's great news, @michaelklishin. Thanks for the update!
