### ISSUE TITLE
Some Python tutorials use queue_declare() without the required queue argument

### ISSUE THREAD

**Issue by glexey** [rabbitmq/rabbitmq-website#780]
Some of queue_declare() examples are missing required queue(str) argument:

```
rabbitmq-website/site/tutorials/tutorial-three-python.md
169:result = channel.queue_declare()
179:result = channel.queue_declare(exclusive=True)

rabbitmq-website/site/tutorials/tutorial-six-python.md
85:result = channel.queue_declare(exclusive=True)
```

    >>> queue_name = channel.queue_declare(exclusive=True)
    TypeError: queue_declare() missing 1 required positional argument: 'queue'

**Comment by michaelklishin** [comment]
They declare [server-named queues](https://www.rabbitmq.com/queues.html) which do not require a name (or rather, the queue name argument is known: an empty string). @lukebakken have we updated the tutorials for Pika 1.0+ API? Does the API require a queue name argument now? (from the looks of the examples, it does?)

**Comment by lukebakken** [comment]
I may have missed this. `queue` is now required, and if you'd like a server-named queue it must be the empty string like this - `queue=''`

**Comment by glexey** [comment]
Some of the tutorials use empty string, as latest Pika docs require, but not all.

**Comment by lukebakken** [comment]
@glexey - A PR to fix this and bring it in line with [this code](https://github.com/rabbitmq/rabbitmq-tutorials/tree/master/python) would be great, thanks.

**Comment by glexey** [comment]
Submitted PR #781

**Comment by lukebakken** [comment]
@glexey thank you for reporting and fixing this, we appreciate it :smile:
