### ISSUE TITLE
Plugin .app file expansion doesn't work for RABBITMQ_BASE paths containing certain characters

### ISSUE THREAD

**Issue by inikulshin** [rabbitmq/rabbitmq-website#786]
Currently RabbitMQ can't be installed in RABBITMQ_BASE path containing symbols `*?[]{}` (or, at least, with certain restrictions)

E.g.

https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_plugins.erl

```
prepare_plugin(#plugin{type = dir, location = Location, name = Name},
               _ExpandDir) ->
    case filelib:wildcard(Location ++ "/ebin/*.app") of
```
must be rewritten as
```
prepare_plugin(#plugin{type = dir, location = Location, name = Name},
               _ExpandDir) ->
    case filelib:wildcard("ebin/*.app", Location) of
```
to enable `Location` with symbols from `*?[]{}` 

Found in **3.6.10** on **Windows**, but it is relevant to all versions and platforms (except `*?`, which are disallowed in Windows paths either)

**Comment by inikulshin** [comment]
Thanks.

> Configuration **Usiing** Environment Variables

You may also want to mention that **Windows** paths must also exclude `!^` (and `*?` are relevant only for **Unix**, because they are not allowed in **Windows** paths anyway)

P.S. Switching to wilcard/2 still seems a tiny effort and not dangerous change to me, but you're the boss.

**Comment by michaelklishin** [comment]
I've filed https://github.com/rabbitmq/rabbitmq-server/issues/2036 for other core team members to evaluate. I will make sure to mention that the list is platform-specific, thanks for the suggestion.
