### ISSUE TITLE
Cloudflare is obfuscating things it presumes are email addresses

### ISSUE THREAD

**Issue by bengaywins** [rabbitmq/rabbitmq-website#796]
As the title states. For example on https://www.rabbitmq.com/cluster-formation.html#peer-discovery-classic-config, anything that is rabbit@node.name.com it is obfuscating thinking it is an email address. Here's the page that Cloudflare has for making sure that it isn't applying to stuff.

https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-

**Comment by michaelklishin** [comment]
Curiously I don't see it but in any case, I have disabled Scrape Shield's obfuscation. Thanks for reporting.
