### ISSUE TITLE
Missing requirements in Server Build Instructions

### ISSUE THREAD

**Issue by Lartza** [rabbitmq/rabbitmq-website#81]
http://www.rabbitmq.com/build-server.html is missing zip and unzip as a requirement.

Also the requirement for Python 2 is not stated while Python 3 is unsupported.

**Comment by videlalvaro** [comment]
Thanks for noticing, BTW, the website is open source if you feel
adventurous and want to submit a PR:
https://github.com/rabbitmq/rabbitmq-website.
