### ISSUE TITLE
Unable to delete binding with undefined routing key

### ISSUE THREAD

**Issue by tomhreb** [rabbitmq/rabbitmq-website#810]
Hi,
RabbitMQ v3.7.15, Erlang v22.0.
When a binding is created through Management API with ```routing_key: null```, it is not possible to delete such binding through DELETE api call: ```/api/bindings/vhost/e/exchange/q/queue/props```.

API returns 405 Method Not Allowed.

Tom

**Comment by tomhreb** [comment]
Wrong repo. sorry.

**Comment by michaelklishin** [comment]
But there are tests in, say, [rabbithole](https://github.com/michaelklishin/rabbit-hole/) that successfully delete bindings. This is mailing list material at this point. Without a specific set of steps to reproduce we direct it to the mailing list in any repository.

**Comment by michaelklishin** [comment]
Also, `null` is a confusing value for clients. Should they leave the value out? Should they pass the `null` value in a path segment? I definitely see how there can be two groups of people with exactly opposite opinions on this.

**Comment by michaelklishin** [comment]
…posted too soon. So I'd suggest using an empty map for "no properties" or manage bindings using a RabbitMQ clients instead. `null` is a confusing value to use in this specific case. Different clients would have different behavior as a result and I personally cannot tell how exactly the API should behave. It's a matter of opinion I'm afraid.
