### ISSUE TITLE
They that shall not be named (typo / erroneous sentence cut)

### ISSUE THREAD

**Issue by t-nelis** [rabbitmq/rabbitmq-website#812]
In [Persistence Configuration, I/O Thread Pool Size](https://github.com/rabbitmq/rabbitmq-website/blob/a14379291bc51ccdadd31e3b4197242603be3e9e/site/persistence-conf.md#io-thread-pool-size):

https://github.com/rabbitmq/rabbitmq-website/blame/a14379291bc51ccdadd31e3b4197242603be3e9e/site/persistence-conf.md#L151

> They are known as These are shared among all virtual hosts and queues.

The sentence is clearly cut by mistake. I couldn't trace any previous version with a quick lookup of the commit log.

So, what are they known as? ;)

**Comment by michaelklishin** [comment]
My bad, I convert guides to Markdown and occasionally introduce formatting problems as mis-edits as I go :) Thank you for reporting, a fix should be live very soon!
