### ISSUE TITLE
CSS is hiding overflow

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-website#845]
Reported here:

https://groups.google.com/d/topic/rabbitmq-users/e_cZDa5XuUo/discussion

**Comment by Ramendra30** [comment]
Hi Luke, I still can't read the Description column clearly. Has the fix been applied ?

**Comment by lukebakken** [comment]
@Ramendra30 please be patient. If you must read that information, you can view it here:

https://github.com/rabbitmq/rabbitmq-website/blob/live/site/configure.md

**Comment by Ramendra30** [comment]
Thanks a lot for the link!!

**Comment by michaelklishin** [comment]
@Ramendra30 the issue is still open and the site still looks the same. #847 is a WIP PR that makes multi-column tables more legiible.

**Comment by michaelklishin** [comment]
A fix (a group of fixes, even) is now live.
