### ISSUE TITLE
3.7.18 upgrade documentation from non-feature flag version needs help

### ISSUE THREAD

**Issue by theRealTurboTime** [rabbitmq/rabbitmq-website#862]
Today my colleagues an I spent close to 1.5 hours trying to figure out why our rolling upgrade 
3.7.12 -> 3.7.18 failed over and over. 

We are not using any feature flags, but to update and prep for 3.8 we want to upgrade rmq in our env.

We encountered numerous errors before we learned that:

1) we need to export RABBITMQ_FEATURE_FLAGS_FILE="/FILE/PATH"
2) If we're not enabling any feature flags that the file shouldn't even exist (can't even be empty)
3) All other nodes need to know about this file. IE:  
   eval "application:set_env(rabbit, feature_flags_file, ['/FILE/PATH'])."

Please update your 'upgrade' documentation with more explicit instructions and explanations on pre 3.8 upgrades with regards to what this feature flags file is, how to format it, and what, if any, feature flags are even available at this point.

If this is in there somewhere, we think this issue report is evidence enough that it's not as visible as it should be.

**Comment by michaelklishin** [comment]
Feature flags are not exposed to the user in 3.7.18. I'm afraid I don't see how a `3.7.12` to `3.7.18` upgrade could be affected by an internally backported feature.

Please start a mailing list discussion and provide a little bit of detail that would allow us to reproduce.

**Comment by michaelklishin** [comment]
FWIW the docs (that now target 3.8) [have a list of feature flags](https://www.rabbitmq.com/feature-flags.html#core-feature-flags). It will be updated as new feature flags are introduced.

**Comment by michaelklishin** [comment]
To explain what we are asking for here: our team uses the mailing list for discussions and investigations. If we find evidence of something that we believe should behave differently in RabbitMQ itself or something incorrect in the docs, we will file a new issue with the uncovered details.

**Comment by michaelklishin** [comment]
Here's [one rabbitmq-users thread](https://groups.google.com/forum/#!msg/rabbitmq-users/4O7ecfgY2IA/QUu7BtBhBAAJ) that seems relevant. There is no real evidence of feature flags having any effect there but in case that's not a member of your team we'd be particularly eager to know how we can reproduce. Two reports is twice as convincing :)
