### ISSUE TITLE
Need explanation for Management Plugin Web UI default account

### ISSUE THREAD

**Issue by HomoEfficio** [rabbitmq/rabbitmq-website#872]
I found the default account 'guest/guest' by the google, not by the rabbitmq Getting Started.

So it would be far better if there was an explanation for the default account in https://www.rabbitmq.com/management.html#usage-ui.

**Comment by michaelklishin** [comment]
There is a separate guide for that. I have pushed an alternative version of your #873. Thanks for contributing.
