### ISSUE TITLE
Foundation of Message Broker

### ISSUE THREAD

**Issue by jt4000** [rabbitmq/rabbitmq-website#883]
Hello,

I'm newbie in relation to RabbitMQ.

What is the benefit to use a message broker?

What context should you use when you use a message broker?

When is the time to use a message broker?

Thank you!

**Comment by michaelklishin** [comment]
Please post your questions to the [mailing list](https://www.rabbitmq.com/contact.html) and take a look at the [tutorials](https://www.rabbitmq.com/getstarted.html).

The question is a bit similar to "when should I use a data store." There are many scenarios that I would not dare to try to list. Messaging technologies allow applications to interact, exchange data, asynchronously act on events and so on. If you have a single application/service then you don't messaging but as soon as you add more, this is something you should at least investigate.

HTH.
