### ISSUE TITLE
A problem about comsumer blocking in production

### ISSUE THREAD

**Issue by chazex** [rabbitmq/rabbitmq-website#892]
When I used rabbit mq, I encountered a problem many times. A new consumer is blocked after spending a few messages, and after the consumer quits, the number of consumers in the "management ui" does not decrease. This happens occasionally when there is more data in the queue. I learned in the official website that when there is more data in the queue (memory usage exceeds the threshold), the producer will be blocked, but the relevant content about blocking consumers is not seen. Can you help explain why? thank.

version: RabbitMQ 3.6.5, Erlang 17.5

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
Consumers are not blocked by resources alarms. I'm afraid we cannot suggest much with the amount of information provided.

RabbitMQ 3.6 has been out of support [for 18 months now](https://www.rabbitmq.com/versions.html) and 3.6.5 specifically is [11 patch releases behind](https://www.rabbitmq.com/changelog.html) even in that series. Consider [upgrading](https://www.rabbitmq.com/upgrade.html).

**Comment by michaelklishin** [comment]
Also worth pointing out that if a connection both publishes and consumes then it is treated as a publisher. No data from that connection will be consumed, including `basic.cancel` and `basic.consume` frames that cancel and add new consumers. A stream of deliveries to existing consumers should not be any different from [regular consumer workloads](https://www.rabbitmq.com/consumers.html).
