### ISSUE TITLE
Line numbers are off (Python Tutorial #6)

### ISSUE THREAD

**Issue by quassy** [rabbitmq/rabbitmq-website#901]
I only checked [part six of the Python tutorial](https://www.rabbitmq.com/tutorials/tutorial-six-python.html) so far, but the line numbers used to describe the source code are off. For example:

> (23) Next, we define our main call method - it does the actual RPC request.

This actually refers to line 25.

> (24) In this method, first we generate a unique correlation_id number and save it - the 'on_response' callback function will use this value to catch the appropriate response.

This actually refers to line 27. And so on.

_Originally reported at rabbitmq/rabbitmq-tutorials/issues/249_

**Comment by michaelklishin** [comment]
You are welcome to contribute a PR with corrections. I'd change the language to not to refer to line numbers where possible.

**Comment by kittitoy69** [comment]
0989306345

**Comment by michaelklishin** [comment]
Python tutorials have seen multiple edits in the last couple of months, let us know if you think this is still relevant.
