### ISSUE TITLE
If we use rabbitmq-peer-discovery-k8s, and want to configure the default cipher suites, can this be configured in asvanced.config?

### ISSUE THREAD

**Issue by AMZ61616AMZ61616** [rabbitmq/rabbitmq-website#909]
If we use rabbitmq-peer-discovery-k8s, and want to configure the default cipher suites, can this be configured in asvanced.config?

_Originally posted by @haiyangu in https://github.com/rabbitmq/rabbitmq-website/issues/567#issuecomment-413734537_

**Comment by lukebakken** [comment]
Not at this time, please see https://github.com/rabbitmq/rabbitmq-peer-discovery-common/issues/9
