### ISSUE TITLE
QS.unescape is not a function

### ISSUE THREAD

**Issue by CrisGarcis** [rabbitmq/rabbitmq-website#948]
amqplib/lib/connect.js:50

**Comment by lukebakken** [comment]
I'm _guessing_ that you are trying to run a tutorial and do not have the correct libraries installed. Please ensure this library is installed:

https://www.npmjs.com/package/amqplib

**Comment by lukebakken** [comment]
@CrisGarcis @FabrizioRicciarelli @vomerfeayli @AyoubKessemtini

First of all, thanks for using RabbitMQ.

#948 is _literally_ one of the least informative issue reports I have yet seen as an open-source maintainer.

Please realize that the people who provide and maintain all of the free software you use have limited time to give you _FREE_ support. The very least you can do is provide a git repository with a complete set of code that demonstrates the issue.

I just took some time to find the use of `QS.unescape` in the `amqplib` module (which Team RabbitMQ **does not maintain**) - https://github.com/amqp-node/amqplib/blob/main/lib/connect.js#L10

Again, like I said in [this comment](https://github.com/rabbitmq/rabbitmq-website/issues/948#issuecomment-595381987), you are trying to use `amqplib` and somehow the `querystring` module is not available in your environment.

Here is what I would consider to be an acceptable set of reproduction steps using the https://github.com/rabbitmq/rabbitmq-tutorials/tree/main/javascript-nodejs repository. Note that it works correctly in my environment -

## Start RabbitMQ

```
$ docker run --pull always --publish 5672:5672 --publish 15672:15672 rabbitmq:3-management
```

## Run tutorial

```
lbakken@shostakovich ~/development/rabbitmq/rabbitmq-tutorials/javascript-nodejs (main =)
$ asdf install nodejs latest
Trying to update node-build... ok
Downloading node-v22.2.0-linux-x64.tar.gz...
-> https://nodejs.org/dist/v22.2.0/node-v22.2.0-linux-x64.tar.gz
Installing node-v22.2.0-linux-x64...
Installed node-v22.2.0-linux-x64 to /home/lbakken/.asdf/installs/nodejs/22.2.0

lbakken@shostakovich ~/development/rabbitmq/rabbitmq-tutorials/javascript-nodejs (main %=)
$ npm install amqplib

added 35 packages, and audited 36 packages in 1s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

lbakken@shostakovich ~/development/rabbitmq/rabbitmq-tutorials/javascript-nodejs (main *%=)
$ node src/send.js
 [x] Sent Hello World!
```

**Comment by lukebakken** [comment]
Here is an example proving that using a vhost named something other than `/` works:

## Start RabbitMQ
```
docker run --rm --interactive --tty --pull always --env RABBITMQ_ALLOW_INPUT=true --publish 5672:5672 --publish 15672:15672 --name rabbitmq rabbitmq:3-management
```

## Add vhost
```
docker exec rabbitmq rabbitmqctl add_vhost issue-948
docker exec rabbitmq rabbitmqctl set_permissions --vhost issue-948 guest '.*' '.*' '.*'
```

## Run code

NOTE: this is the code: https://github.com/lukebakken/rabbitmq-website-948/blob/rabbitmq-website-948/javascript-nodejs/src/send.js#L5

```
lbakken@shostakovich ~/development/rabbitmq/rabbitmq-tutorials/javascript-nodejs (rabbitmq-website-948 =)
$ node src/send.js
 [x] Sent Hello World!
```

----

@CrisGarcis @FabrizioRicciarelli @vomerfeayli @AyoubKessemtini

If any of you _really_ wish to get assistance, help us help you by providing a way to reproduce the issue.

**Comment by michaelklishin** [comment]
@lukebakken I can add that in several HTTP API client libraries we use generated virtual host names that are not ASCII and include plenty of punctuation characters. This has been the case since 2015 or so.

That's as much as can be said with the problem definition of

> amqplib/lib/connect.js:50
