### ISSUE TITLE
Point out quorum queue resource recommendations at production checklist

### ISSUE THREAD

**Issue by dreiucker** [rabbitmq/rabbitmq-website#952]
The current [ Production Checklist ](https://www.rabbitmq.com/production-checklist.html#resource-limits-ram) is referencing a minimal memory limit of 128 MB
> Nodes hosting RabbitMQ should have at least 128MB of memory available at all times.

However, if you consider now using  [quorum queues](https://www.rabbitmq.com/quorum-queues.html#resource-use) the minimal memory limit doesn't fit together anymore:

> The WAL file size limit at which memory and disk start being released defaults to 512MiB.
> 
> Because memory deallocation may take some time, we recommend that the RabbitMQ node is allocated at least 3 times the memory of the default WAL file size limit. More will be required in high-throughput systems. 4 times is a good starting point for those.

Of course you can say that people should have read both documentations when they are considering using their system in production + using quorum queues. Still if the default recommendation for a production does change by a feature I would at least expect to find a pointer in the production checklist.

**Comment by michaelklishin** [comment]
It's possible to cap the amount of memory key a quorum queue log uses (and it is the biggest contributor by far). I've bumped changed the recommendation to 256 MiB and added a few links.

**Comment by dreiucker** [comment]
Thank you, that was fast 👍
