### ISSUE TITLE
Incorrect quorum queues exclusivity doc?

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-website#957]
https://www.rabbitmq.com/quorum-queues.html says:

**Exclusivity**
Regular queues can be exlusive. Quorum queues are always durable per their assumed use cases. They are not meant to be used as temporary queues.

How is durability related to exclusivity? There is also a typo in "exlusive".

**Comment by michaelklishin** [comment]
It makes no sense to have durable exclusive queues since an exclusive queue's lifetime is based on that of a connection. Classic exclusive queues are not replicated at all even if a mirroring policy applies to them, for that reason.
