### ISSUE TITLE
Explicit mentioning of bundling of server+client tools 

### ISSUE THREAD

**Issue by MrAmbiG** [rabbitmq/rabbitmq-website#958]
https://www.rabbitmq.com/rabbitmqctl.8.html
I Could no where find explicit information that rabbitmqctl is not a downloadable client but it is bundled with server only. Your website is a bit ambiguous or unclear whether the cli tools come with *only* server installation and thus available only on the server or whether they can be downloaded separately and run against a remote server. 
ex 1:- psql client can be downloaded separately and run against a remote server. The psql client is separate from postgresql db itself and it is not available with the installation of the server.
ex 2:- hashicorp vault is one tool which can be used as both client and server. a hashicorp vault bin file can be run against a remote or local server.
Please explicitly mention that the cli tools which are integrated with the server and which are separate from the server. Reader should not wonder about whether they have to download it or run directly on the server or can they do both?
RabbitMQ is exceptional and way ahead of any of its competitors (if there are any) in what it does. Let the documentation also be explicit if not exceptional.

**Comment by michaelklishin** [comment]
We have just deployed several updates (https://github.com/rabbitmq/rabbitmq-website/commit/2014c8be4da535b1cacd20bd2bf389d7a93bc2fa, https://github.com/rabbitmq/rabbitmq-website/commit/1180c6ca906f8a7387510283363dc2f25dfde931) to the [CLI tools guide](https://www.rabbitmq.com/cli.html?skip_cache=1) that clarify this. man pages are not deployed continuously so any updates we may decide to do there will ship around the time of the next release.

As for shipping CLI tools separately, I filed https://github.com/rabbitmq/rabbitmq-server-release/issues/122 for consideration. Obviously, we won't be removing them from the server distribution that's basically been this way for 13 years but it should be reasonably easy to distribute just CLI tools as a separate package or two.
