### ISSUE TITLE
.net: Tutorial one does not compile

### ISSUE THREAD

**Issue by zanseb** [rabbitmq/rabbitmq-website#963]
The `.net tutorial one` does not compile using .net core.
I do not use this library but I came across this issue on [stackoverflow](https://stackoverflow.com/q/61374796/7155909).

The code example in the [`receving`](https://github.com/rabbitmq/rabbitmq-website/blob/a39671ca282adc3ab0669120be621af3d0f44e15/site/tutorials/tutorial-one-dotnet.md#receiving) section tries to pass the [`Body`](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/8617745f7ef20648e11a3e24c5b8f8964e5da204/projects/RabbitMQ.Client/client/events/BasicDeliverEventArgs.cs#L77) of `BasicDeliverEventArgs ` to the method `Encoding.UTF8.GetString`. That does not compile, because `Encoding.UTF8.GetString` has no overload for `ReadOnlyMemory<byte>`. In order to achieve that `ReadOnlySpan<byte>` has to be used, which can be accessed via the `.Span` property of `ReadOnlyMemory<byte>`.

HTH

**Comment by lukebakken** [comment]
Fixed by https://github.com/rabbitmq/rabbitmq-website/commit/a701a755747d10c2917ffcd37a5fd4ce870f81b6
