### ISSUE TITLE
Ambiguous 32- vs. 64-bit reference in 'site/install-windows-manual.md'

### ISSUE THREAD

**Issue by olamartensson** [rabbitmq/rabbitmq-website#978]
In file `site/install-windows-manual.md`:

Row 28:
> RabbitMQ requires a **64-bit** supported version of Erlang

Row 33-34:
> depending on your platform and whether you chose a **32bit or 64bit** version of Erlang

Is it supported to run RabbitMQ on 32-bit Windows with 32-bit Erlang or not?

**Comment by michaelklishin** [comment]
Technically RabbitMQ does not care but due to the obvious memory address space limitation, it is not a practical option for data services. So such environments should not be considered supported.

I'd highly recommend using Chocolatey or the install for most people over manual installation.
