### ISSUE TITLE
Inconsistency around RABBITMQ_CONFIG_FILE in docs

### ISSUE THREAD

**Issue by harshac** [rabbitmq/rabbitmq-website#979]
I. The supported [environment variables section](https://www.rabbitmq.com/configure.html#supported-environment-variables) mentions

`Main RabbitMQ config file path without the .conf (or .config, for the classic format) extension. For example, it should be /data/rabbitmq/rabbitmq, not /data/rabbitmq/rabbitmq.conf`. 

Reading this, we understand that we shouldn't add `.conf`when setting the `RABBITMQ_CONFIG_FILE` env variable.

II. [Configuration using config file linux section](https://www.rabbitmq.com/configure.html#environment-env-file-unix) example image however configures `CONFIG_PATH` with `.conf` in the end. 

III. In this [section](https://www.rabbitmq.com/configure.html#config-file), the last line is a little confusing. 
`To override the main RabbitMQ config file location, use the RABBITMQ_CONFIG_FILE environment variable. Use .conf as file extension for the new style config format.` 

We had different opinions what it meant

1.
```
$ ls $RABBITMQ_HOME/etc/rabbitmq
rabbitmq.conf

$ echo $RABBITMQ_CONFIG_FILE
/rmq_home/etc/rabbitmq/rabbitmq
```

2.
```
$ ls $RABBITMQ_HOME/etc/rabbitmq
rabbitmq

$ echo $RABBITMQ_CONFIG_FILE
/rmq_home/etc/rabbitmq/rabbitmq
```

**Action:**
Reword the docs to express the correct opinions. Modify the example image to reflect the same. 

CC @ablease

**Comment by michaelklishin** [comment]
Before 3.7.0, the exception was required to be omitted. This is how Erlang works, the `.config` is appended to the provided value. This was confusing to enough users that we found a way to work around this limitation so the extension could be omitted.

For `rabbitmq.conf`, which is a source for the final config file which a tool called Cuttlefish generates, there was never such as convention in place.
