### ISSUE TITLE
Minor problems with .NET tutorial two

### ISSUE THREAD

**Issue by glennsills** [rabbitmq/rabbitmq-website#981]
1. In Worker class
```             
var body = ea.Body;
var message = Encoding.UTF8.GetString(body);
```
will not compile. ea.Body is a ReadonlyMemory<byte>. You have to convert it to  a byte array like so:
```
var body = ea.Body.ToArray();
```
2. It would be nice if you explained that you have to run newtask first and then worker so that the queue gets created and then explain why.

**Comment by michaelklishin** [comment]
This documentation is open source so you are welcome to contribute changes as pull requests.

The Putting it All Together section in tutorial one already recommended running the consumer app first. Now tutorial two does the same.
