### ISSUE TITLE
Document that system TLS cert stores are not used by Erlang

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-website#987]
Frequently, users are surprised that Erlang's TLS implementation does not use the system certificate stores for establishing the trust chain. Most recently this came up in the public slack channel with regard to the use of Let's Encrypt certificates -

https://rabbitmq.slack.com/archives/C1EDN83PA/p1591967717131700

This page should be updated to make this clearer, and perhaps provide an example using Let's Encrypt -

https://github.com/rabbitmq/rabbitmq-website/blob/live/site/ssl.md

**Comment by michaelklishin** [comment]
We did it in https://github.com/rabbitmq/rabbitmq-website/commit/40a9185d19e8a0df8ea80c3930846570c0f02efb

**Comment by lukebakken** [comment]
Thanks for pointing that out @michaelklishin - https://www.rabbitmq.com/ssl.html#peer-verification-trusted-certificates

@ydbondt - please review the documentation to see if it is explained well-enough - https://www.rabbitmq.com/ssl.html#peer-verification-trusted-certificates

**Comment by michaelklishin** [comment]
We would definitely consider a new section that covers Let's Encrypt, if contributed.
